-- =====================================================
-- Lexis AI
-- schema.sql — COMPLETE PRODUCTION SCHEMA
-- PostgreSQL 16+
--
-- Domains:
--   1. Extensions + Utility
--   2. Enums
--   3. Content Domain      (books, chapters, source_chunks,
--                           concepts, concept_edges,
--                           concept_chunks, generated_questions,
--                           graph_build_jobs)
--   4. User Domain         (users, user_books,
--                           learner_profiles, learning_dna)
--   5. Assessment Domain   (assessments, assessment_responses,
--                           assessment_outcomes)
--   6. Learning Domain     (curriculum_plans, lesson_sessions,
--                           tutor_interactions)
--   7. Mastery Domain      (user_concept_state, concept_mastery,
--                           concept_fsrs, fsrs_reviews,
--                           mastery_events)
--   8. Gamification Domain (content_completions, daily_activity,
--                           learning_streaks, book_streaks,
--                           progress_snapshots)
--   9. Analytics           (materialized views + helper views)
--  10. Production Layer    (indexes, constraints, functions,
--                           tsvector search, comments)
--
-- Total: 26 tables + 3 materialized views + 4 views
-- =====================================================

-- =====================================================
-- EXTENSIONS
-- =====================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =====================================================
-- UTILITY TRIGGER FUNCTION
-- =====================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

-- =====================================================
-- ENUMS
-- =====================================================

-- Books
CREATE TYPE book_status AS ENUM (
    'UPLOADING',
    'PARSING',
    'EXTRACTING_CONCEPTS',
    'KG_BUILT',
    'KG_VERIFIED',
    'READY',
    'FAILED',
    'ARCHIVED'
);

CREATE TYPE book_visibility AS ENUM (
    'PUBLIC',
    'PRIVATE',
    'TEAM'
);

-- Graph
CREATE TYPE graph_build_status AS ENUM (
    'QUEUED',
    'PARSING',
    'EXTRACTING_CONCEPTS',
    'BUILDING_GRAPH',
    'VALIDATING',
    'COMPLETED',
    'FAILED'
);

CREATE TYPE edge_type AS ENUM (
    'PREREQUISITE',
    'RELATED'
);

-- Questions
CREATE TYPE question_type AS ENUM (
    'MCQ',
    'TRUE_FALSE',
    'SHORT_ANSWER',
    'SCENARIO',
    'ORDERING',
    'MATCHING'
);

CREATE TYPE question_source AS ENUM (
    'GENERATED',
    'USER_ASKED',
    'ASSESSMENT_MISS',
    -- REVISION: questions auto-generated by FSRS revision engine
    -- (distinct from GENERATED which comes from the ingestion pipeline)
    'REVISION'
);

-- Users
CREATE TYPE user_role AS ENUM (
    'STUDENT',
    'ADMIN'
);

CREATE TYPE experience_level AS ENUM (
    'BEGINNER',
    'INTERMEDIATE',
    'ADVANCED'
);

-- Assessments
CREATE TYPE assessment_type AS ENUM (
    'INITIAL',
    'PLACEMENT',
    'CHAPTER',
    'REVISION'
);

CREATE TYPE assessment_status AS ENUM (
    'DRAFT',
    'IN_PROGRESS',
    'COMPLETED',
    'ABANDONED'
);

CREATE TYPE placement_state AS ENUM (
    'MASTERED',
    'READY',
    'LEARNING',
    'WEAK',
    'UNKNOWN'
);

-- Learning
CREATE TYPE lesson_status AS ENUM (
    'NOT_STARTED',
    'IN_PROGRESS',
    'COMPLETED',
    'ABANDONED'
);

-- Mastery
-- NOTE: node_state drives the DAG-gated UI reveal.
-- LOCKED      — prerequisites not met
-- AVAILABLE   — unlocked, not started
-- IN_PROGRESS — currently being learned
-- MASTERED    — cleared the mastery threshold
-- DUE         — mastered but FSRS says review needed
CREATE TYPE node_state AS ENUM (
    'LOCKED',
    'AVAILABLE',
    'IN_PROGRESS',
    'MASTERED',
    'DUE'
);

CREATE TYPE mastery_state AS ENUM (
    'UNKNOWN',
    'LEARNING',
    'PRACTICING',
    'MASTERED',
    'FORGOTTEN'
);

CREATE TYPE review_source AS ENUM (
    'ASSESSMENT',
    'LESSON',
    'QUIZ',
    'REVISION',
    'MANUAL'
);

-- =====================================================
-- 1. CONTENT DOMAIN
-- =====================================================

-- -----------------------------------------------------
-- BOOKS
-- -----------------------------------------------------
-- owner_id references users. Added after users table,
-- so FK is deferred — kept nullable + constraint added
-- after users table creation.
-- Design: { id, owner_id, title, source_file, status }
-- Status lifecycle: UPLOADING → PARSING →
--   EXTRACTING_CONCEPTS → KG_BUILT → KG_VERIFIED → READY
-- -----------------------------------------------------

CREATE TABLE books (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- owner_id FK added after users table
    owner_id UUID,

    title TEXT NOT NULL,

    author TEXT,

    description TEXT,

    source_type VARCHAR(50) NOT NULL
        CHECK (source_type IN ('PDF', 'EPUB', 'TXT', 'DOCX', 'URL')),

    file_url TEXT NOT NULL,

    file_size_bytes BIGINT,

    page_count INTEGER,

    language VARCHAR(10) NOT NULL DEFAULT 'en',

    status book_status NOT NULL DEFAULT 'UPLOADING',

    visibility book_visibility NOT NULL DEFAULT 'PRIVATE',

    -- current_graph_version deliberately omitted.
    -- The canonical current version is derived from:
    --   SELECT version FROM graph_versions
    --   WHERE book_id = ? AND is_current = TRUE
    -- Storing a redundant integer here would introduce
    -- a second source of truth that can drift.

    processing_started_at TIMESTAMPTZ,

    processing_completed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_page_count
        CHECK (page_count IS NULL OR page_count > 0),

    CONSTRAINT chk_processing_time
        CHECK (
            processing_completed_at IS NULL
            OR processing_started_at IS NULL
            OR processing_completed_at >= processing_started_at
        )
);

CREATE INDEX idx_books_status ON books(status);
CREATE INDEX idx_books_owner  ON books(owner_id);
CREATE INDEX idx_books_visibility ON books(visibility);
CREATE INDEX idx_books_created_at ON books(created_at DESC);
CREATE INDEX idx_books_title ON books(title);

CREATE TRIGGER trg_books_updated_at
BEFORE UPDATE ON books
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------
-- CHAPTERS
-- -----------------------------------------------------

CREATE TABLE chapters (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    book_id UUID NOT NULL
        REFERENCES books(id)
        ON DELETE CASCADE,

    chapter_number INTEGER NOT NULL,

    title TEXT NOT NULL,

    summary TEXT,

    estimated_minutes INTEGER,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_chapter_number   CHECK (chapter_number > 0),
    CONSTRAINT chk_estimated_minutes CHECK (estimated_minutes IS NULL OR estimated_minutes > 0),
    CONSTRAINT uq_book_chapter_number UNIQUE (book_id, chapter_number)
);

CREATE INDEX idx_chapters_book_id ON chapters(book_id);
CREATE INDEX idx_chapters_number  ON chapters(book_id, chapter_number);

CREATE TRIGGER trg_chapters_updated_at
BEFORE UPDATE ON chapters
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------
-- SOURCE CHUNKS
-- -----------------------------------------------------
-- Every node is traceable back to the chunk of book
-- text it came from (teaching + trust).
-- -----------------------------------------------------

CREATE TABLE source_chunks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    book_id UUID NOT NULL
        REFERENCES books(id)
        ON DELETE CASCADE,

    chapter_id UUID
        REFERENCES chapters(id)
        ON DELETE SET NULL,

    chunk_index INTEGER NOT NULL,

    content TEXT NOT NULL,

    token_count INTEGER,

    -- page_start/end for citation rendering in tutor
    page_start INTEGER,

    page_end INTEGER,

    metadata JSONB,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_chunk_index   CHECK (chunk_index >= 0),
    CONSTRAINT chk_token_count   CHECK (token_count IS NULL OR token_count > 0),
    CONSTRAINT chk_page_numbers  CHECK (
        (page_start IS NULL AND page_end IS NULL)
        OR (page_start IS NOT NULL AND page_end IS NOT NULL AND page_end >= page_start)
    ),
    CONSTRAINT uq_chunk_position UNIQUE (book_id, chunk_index)
);

CREATE INDEX idx_source_chunks_book     ON source_chunks(book_id);
CREATE INDEX idx_source_chunks_chapter  ON source_chunks(chapter_id);
CREATE INDEX idx_source_chunks_position ON source_chunks(book_id, chunk_index);
CREATE INDEX idx_source_chunks_metadata ON source_chunks USING GIN(metadata);

-- -----------------------------------------------------
-- CONCEPTS  (KG Nodes)
-- -----------------------------------------------------
-- Design: { id, book_id, title, summary,
--           source_chunks[], difficulty_tier }
-- search_vector populated by application on write
-- (or via trigger). Using tsvector for book search.
-- -----------------------------------------------------

CREATE TABLE concepts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    book_id UUID NOT NULL
        REFERENCES books(id)
        ON DELETE CASCADE,

    chapter_id UUID
        REFERENCES chapters(id)
        ON DELETE SET NULL,

    -- allows merging duplicate concepts across graph versions
    canonical_concept_id UUID
        REFERENCES concepts(id)
        ON DELETE SET NULL,

    name TEXT NOT NULL,

    summary TEXT NOT NULL,

    learning_objective TEXT,

    -- 1=novice, 2=easy, 3=medium, 4=hard, 5=expert
    difficulty_level INTEGER NOT NULL,

    estimated_minutes INTEGER,

    graph_version INTEGER NOT NULL DEFAULT 1,

    metadata JSONB,

    -- tsvector for full-text search on concept name + summary
    search_vector tsvector,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_concept_difficulty
        CHECK (difficulty_level >= 1 AND difficulty_level <= 5),

    CONSTRAINT chk_concept_minutes
        CHECK (estimated_minutes IS NULL OR estimated_minutes > 0),

    CONSTRAINT chk_concept_graph_version
        CHECK (graph_version > 0),

    -- Prevent duplicate concept names per book per graph version
    CONSTRAINT uq_concept_book_name_version
        UNIQUE (book_id, name, graph_version)
);

CREATE INDEX idx_concepts_book         ON concepts(book_id);
CREATE INDEX idx_concepts_chapter      ON concepts(chapter_id);
CREATE INDEX idx_concepts_canonical    ON concepts(canonical_concept_id);
CREATE INDEX idx_concepts_difficulty   ON concepts(difficulty_level);
CREATE INDEX idx_concepts_graph_version ON concepts(book_id, graph_version);
CREATE INDEX idx_concepts_metadata     ON concepts USING GIN(metadata);
CREATE INDEX idx_concepts_name         ON concepts(name);
CREATE INDEX idx_concepts_search       ON concepts USING GIN(search_vector);

CREATE TRIGGER trg_concepts_updated_at
BEFORE UPDATE ON concepts
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------
-- CONCEPT_EDGES  (KG Edges — DAG)
-- -----------------------------------------------------
-- THE MOST CRITICAL TABLE.
-- Design: { from_node, to_node, type: prerequisite|related,
--            weight, confidence }
--
-- DAG INVARIANT:
--   Prerequisite edges MUST form a Directed Acyclic Graph.
--   Cycle detection runs in the ingestion pipeline (step 3)
--   BEFORE insertion using a topological sort. Any edge that
--   would create a cycle is rejected at the application layer.
--   The graph_build_job status moves to FAILED if a cycle is
--   detected after LLM extraction.
--
--   Viva answer: "We cannot enforce acyclicity purely in SQL
--   without a recursive CTE check on every INSERT (too
--   expensive). Instead, the pipeline validates the full edge
--   set with Kahn's algorithm before committing any edges.
--   The COMPLETED graph_build_job is proof of validation."
--
-- CROSS-BOOK INTEGRITY:
--   Nothing in the FK model prevents an edge where
--   from_concept.book_id != edge.book_id. This is enforced
--   by a BEFORE INSERT/UPDATE trigger below (trg_edge_same_book).
--
-- Edge semantics:
--   PREREQUISITE: from_node must be mastered before to_node
--                 is unlocked. to_node depends on from_node.
--   RELATED:      Informational link, no locking effect.
-- -----------------------------------------------------

CREATE TABLE concept_edges (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    book_id UUID NOT NULL
        REFERENCES books(id)
        ON DELETE CASCADE,

    graph_version INTEGER NOT NULL DEFAULT 1,

    from_concept_id UUID NOT NULL
        REFERENCES concepts(id)
        ON DELETE CASCADE,

    to_concept_id UUID NOT NULL
        REFERENCES concepts(id)
        ON DELETE CASCADE,

    edge_type edge_type NOT NULL DEFAULT 'PREREQUISITE',

    -- 0.0–1.0, LLM-generated confidence score for this edge
    confidence NUMERIC(5,4) NOT NULL DEFAULT 0.5,

    -- optional weight for graph traversal ordering
    weight NUMERIC(5,4) NOT NULL DEFAULT 1.0,

    -- edges flagged as human-verified skip re-validation
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_concept_edge
        UNIQUE (book_id, graph_version, from_concept_id, to_concept_id, edge_type),

    CONSTRAINT chk_no_self_loop
        CHECK (from_concept_id <> to_concept_id),

    CONSTRAINT chk_confidence
        CHECK (confidence >= 0 AND confidence <= 1),

    CONSTRAINT chk_weight
        CHECK (weight >= 0),

    CONSTRAINT chk_graph_version_edge
        CHECK (graph_version > 0)
);

CREATE INDEX idx_concept_edges_book        ON concept_edges(book_id, graph_version);
CREATE INDEX idx_concept_edges_from        ON concept_edges(from_concept_id);
CREATE INDEX idx_concept_edges_to          ON concept_edges(to_concept_id);
CREATE INDEX idx_concept_edges_type        ON concept_edges(edge_type);
CREATE INDEX idx_concept_edges_unverified  ON concept_edges(book_id) WHERE is_verified = FALSE;

-- -----------------------------------------------------
-- CROSS-BOOK EDGE INTEGRITY TRIGGER
-- -----------------------------------------------------
-- Ensures both endpoint concepts belong to edge.book_id.
-- Prevents: concept from book A → concept from book B
-- which the FK model alone cannot prevent.
-- -----------------------------------------------------

CREATE OR REPLACE FUNCTION enforce_edge_same_book()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    from_book UUID;
    to_book   UUID;
BEGIN
    SELECT book_id INTO from_book FROM concepts WHERE id = NEW.from_concept_id;
    SELECT book_id INTO to_book   FROM concepts WHERE id = NEW.to_concept_id;

    IF from_book IS DISTINCT FROM NEW.book_id THEN
        RAISE EXCEPTION
            'concept_edges integrity: from_concept_id % belongs to book %, not edge.book_id %',
            NEW.from_concept_id, from_book, NEW.book_id;
    END IF;

    IF to_book IS DISTINCT FROM NEW.book_id THEN
        RAISE EXCEPTION
            'concept_edges integrity: to_concept_id % belongs to book %, not edge.book_id %',
            NEW.to_concept_id, to_book, NEW.book_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_edge_same_book
BEFORE INSERT OR UPDATE ON concept_edges
FOR EACH ROW EXECUTE FUNCTION enforce_edge_same_book();

-- -----------------------------------------------------
-- CONCEPT CHUNKS  (concept ↔ source mapping)
-- -----------------------------------------------------

CREATE TABLE concept_chunks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    concept_id UUID NOT NULL
        REFERENCES concepts(id)
        ON DELETE CASCADE,

    chunk_id UUID NOT NULL
        REFERENCES source_chunks(id)
        ON DELETE CASCADE,

    relevance_score NUMERIC(5,4),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_concept_chunk UNIQUE (concept_id, chunk_id),

    CONSTRAINT chk_relevance_score
        CHECK (relevance_score IS NULL
               OR (relevance_score >= 0 AND relevance_score <= 1))
);

CREATE INDEX idx_concept_chunks_concept ON concept_chunks(concept_id);
CREATE INDEX idx_concept_chunks_chunk   ON concept_chunks(chunk_id);

-- -----------------------------------------------------
-- GENERATED QUESTIONS
-- -----------------------------------------------------
-- Design: { id, node_id, type: mcq|theory|applied,
--            difficulty, source: generated|user_asked|assessment_miss }
-- source field powers targeted revision — do NOT drop it.
-- -----------------------------------------------------

CREATE TABLE generated_questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    concept_id UUID NOT NULL
        REFERENCES concepts(id)
        ON DELETE CASCADE,

    question_type question_type NOT NULL,

    -- Where this question originated
    question_source question_source NOT NULL DEFAULT 'GENERATED',

    difficulty_level INTEGER NOT NULL,

    question_text TEXT NOT NULL,

    -- JSONB: MCQ options, correct answers, etc.
    answer_key JSONB NOT NULL,

    explanation TEXT,

    generation_model VARCHAR(100),

    generation_version VARCHAR(50),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_question_difficulty
        CHECK (difficulty_level >= 1 AND difficulty_level <= 5)
);

CREATE INDEX idx_generated_questions_concept    ON generated_questions(concept_id);
CREATE INDEX idx_generated_questions_type       ON generated_questions(question_type);
CREATE INDEX idx_generated_questions_source     ON generated_questions(question_source);
CREATE INDEX idx_generated_questions_difficulty ON generated_questions(difficulty_level);
CREATE INDEX idx_generated_questions_answer_key ON generated_questions USING GIN(answer_key);

-- Targeted revision query: find assessment_miss questions for a user's weak concepts
CREATE INDEX idx_generated_questions_concept_source
    ON generated_questions(concept_id, question_source);

-- -----------------------------------------------------
-- GRAPH BUILD JOBS
-- -----------------------------------------------------
-- Tracks async pipeline runs. One job per version attempt.
-- Only one COMPLETED version can exist per book (enforced
-- via partial unique below instead of blanket unique, so
-- FAILED retries don't block).
-- -----------------------------------------------------

CREATE TABLE graph_build_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    book_id UUID NOT NULL
        REFERENCES books(id)
        ON DELETE CASCADE,

    graph_version INTEGER NOT NULL,

    status graph_build_status NOT NULL DEFAULT 'QUEUED',

    started_at TIMESTAMPTZ,

    completed_at TIMESTAMPTZ,

    nodes_created INTEGER,

    edges_created INTEGER,

    concepts_created INTEGER,

    chunks_processed INTEGER,

    error_message TEXT,

    metadata JSONB,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_graph_version_positive CHECK (graph_version > 0),
    CONSTRAINT chk_nodes_created    CHECK (nodes_created    IS NULL OR nodes_created >= 0),
    CONSTRAINT chk_edges_created    CHECK (edges_created    IS NULL OR edges_created >= 0),
    CONSTRAINT chk_concepts_created CHECK (concepts_created IS NULL OR concepts_created >= 0),
    CONSTRAINT chk_chunks_processed CHECK (chunks_processed IS NULL OR chunks_processed >= 0),
    CONSTRAINT chk_graph_job_time   CHECK (
        completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at
    )
);

CREATE INDEX idx_graph_build_jobs_book     ON graph_build_jobs(book_id);
CREATE INDEX idx_graph_build_jobs_status   ON graph_build_jobs(status);
CREATE INDEX idx_graph_build_jobs_version  ON graph_build_jobs(book_id, graph_version);
CREATE INDEX idx_graph_build_jobs_metadata ON graph_build_jobs USING GIN(metadata);

-- Only one COMPLETED build per (book, graph_version)
CREATE UNIQUE INDEX uq_completed_graph_version
    ON graph_build_jobs(book_id, graph_version)
    WHERE status = 'COMPLETED';

-- -----------------------------------------------------
-- GRAPH_VERSIONS
-- -----------------------------------------------------
-- Named registry of every successfully completed graph
-- build per book. Single authoritative source for all
-- version lookups — replaces free integers across:
--   concepts.graph_version
--   concept_edges.graph_version
--   user_concept_state.graph_version
--
-- Design decisions encoded here:
--   1. books has NO current_graph_version column.
--      Current version = graph_versions WHERE is_current = TRUE.
--      One source of truth, enforced by trigger below.
--
--   2. user_books.pinned_graph_version_id is a UUID FK
--      to this table (ON DELETE RESTRICT), guaranteeing
--      every enrolled user references a real, validated
--      graph version. Naked integers are gone.
--
--   3. user_concept_state.graph_version is still a bare
--      INTEGER (joining through graph_versions to validate
--      it on every write would be expensive). It is an
--      application invariant: always set it from
--      graph_versions.version at write time.
--
-- Note: Only COMPLETED build jobs get a row here.
-- FAILED attempts stay in graph_build_jobs only.
-- -----------------------------------------------------

CREATE TABLE graph_versions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    book_id UUID NOT NULL
        REFERENCES books(id)
        ON DELETE CASCADE,

    -- The integer version key (matches graph_build_jobs.graph_version,
    -- concepts.graph_version, concept_edges.graph_version)
    version INTEGER NOT NULL,

    -- FK back to the build job that produced this version
    build_job_id UUID NOT NULL
        REFERENCES graph_build_jobs(id)
        ON DELETE RESTRICT,

    -- Denormalised counts for fast info display (no join needed)
    node_count INTEGER NOT NULL DEFAULT 0,

    edge_count INTEGER NOT NULL DEFAULT 0,

    -- Human-readable label e.g. "v1 — initial build", "v2 — post-review"
    label TEXT,

    is_current BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_graph_version_per_book UNIQUE (book_id, version),

    CONSTRAINT chk_gv_version    CHECK (version > 0),
    CONSTRAINT chk_gv_node_count CHECK (node_count >= 0),
    CONSTRAINT chk_gv_edge_count CHECK (edge_count >= 0)
);

CREATE INDEX idx_graph_versions_book    ON graph_versions(book_id);
CREATE INDEX idx_graph_versions_current ON graph_versions(book_id) WHERE is_current = TRUE;

-- Enforce exactly ONE is_current = TRUE per book
CREATE UNIQUE INDEX uq_current_graph_version_per_book
    ON graph_versions(book_id)
    WHERE is_current = TRUE;

-- Trigger: when a new graph_versions row is set is_current = TRUE,
-- automatically demote all other versions for that book.
CREATE OR REPLACE FUNCTION enforce_one_current_graph_version()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.is_current = TRUE THEN
        UPDATE graph_versions
        SET    is_current = FALSE
        WHERE  book_id = NEW.book_id
          AND  id      <> NEW.id
          AND  is_current = TRUE;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_one_current_graph_version
AFTER INSERT OR UPDATE OF is_current ON graph_versions
FOR EACH ROW
WHEN (NEW.is_current = TRUE)
EXECUTE FUNCTION enforce_one_current_graph_version();


-- =====================================================
-- 2. USER DOMAIN
-- =====================================================

-- -----------------------------------------------------
-- USERS
-- -----------------------------------------------------

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    email VARCHAR(255) NOT NULL UNIQUE,

    password_hash TEXT NOT NULL,

    full_name VARCHAR(255) NOT NULL,

    role user_role NOT NULL DEFAULT 'STUDENT',

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    last_login_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role  ON users(role);
CREATE INDEX idx_users_active ON users(is_active) WHERE is_active = TRUE;

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Now that users table exists, add FK from books.owner_id
ALTER TABLE books
    ADD CONSTRAINT fk_books_owner
    FOREIGN KEY (owner_id)
    REFERENCES users(id)
    ON DELETE SET NULL;

-- -----------------------------------------------------
-- USER_BOOKS
-- -----------------------------------------------------
-- Junction: a user enrolls in a book.
-- pinned_graph_version_id: FK to graph_versions.
--   Locks the user to the exact graph version that existed
--   when they enrolled, so upstream graph rebuilds don't
--   silently break their in-progress learning path.
--   ON DELETE RESTRICT prevents accidental deletion of a
--   graph version that users are actively enrolled on.
-- -----------------------------------------------------

CREATE TABLE user_books (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    book_id UUID NOT NULL
        REFERENCES books(id)
        ON DELETE CASCADE,

    -- FK to graph_versions — typed, validated, no free integers
    pinned_graph_version_id UUID NOT NULL
        REFERENCES graph_versions(id)
        ON DELETE RESTRICT,

    current_chapter_id UUID
        REFERENCES chapters(id)
        ON DELETE SET NULL,

    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    last_activity_at TIMESTAMPTZ,

    completed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_user_book UNIQUE (user_id, book_id)
);

CREATE INDEX idx_user_books_user    ON user_books(user_id);
CREATE INDEX idx_user_books_book    ON user_books(book_id);
CREATE INDEX idx_user_books_version ON user_books(pinned_graph_version_id);

CREATE TRIGGER trg_user_books_updated_at
BEFORE UPDATE ON user_books
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------
-- LEARNER PROFILES
-- -----------------------------------------------------

CREATE TABLE learner_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL UNIQUE
        REFERENCES users(id)
        ON DELETE CASCADE,

    confidence_level INTEGER,

    experience_level experience_level,

    preferred_examples VARCHAR(100),

    learning_velocity VARCHAR(20),

    preferred_study_minutes INTEGER,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_confidence
        CHECK (confidence_level IS NULL
               OR (confidence_level >= 1 AND confidence_level <= 5)),

    CONSTRAINT chk_study_minutes
        CHECK (preferred_study_minutes IS NULL OR preferred_study_minutes > 0)
);

CREATE TRIGGER trg_learner_profiles_updated_at
BEFORE UPDATE ON learner_profiles
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------
-- LEARNING DNA
-- -----------------------------------------------------
-- Personalized learner model, versioned. Append-only.
--
-- is_active: exactly ONE row per user should be active
-- at any time. Enforced by trg_one_active_dna trigger.
-- Activating a new version deactivates all prior ones.
--
-- Design decision: is_active over MAX(dna_version)
-- because it's explicit, queryable with a partial index,
-- and survives version resets without ambiguity.
-- -----------------------------------------------------

CREATE TABLE learning_dna (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    dna_version INTEGER NOT NULL,

    dna_data JSONB NOT NULL,

    is_active BOOLEAN NOT NULL DEFAULT FALSE,

    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_dna_version CHECK (dna_version > 0),

    CONSTRAINT uq_user_dna_version UNIQUE (user_id, dna_version)
);

CREATE INDEX idx_learning_dna_user   ON learning_dna(user_id);
CREATE INDEX idx_learning_dna_data   ON learning_dna USING GIN(dna_data);

-- Fast lookup: "what is this user's current DNA?"
CREATE UNIQUE INDEX uq_active_dna_per_user
    ON learning_dna(user_id)
    WHERE is_active = TRUE;

-- -----------------------------------------------------
-- ONE ACTIVE DNA TRIGGER
-- -----------------------------------------------------
-- When a new DNA row is set is_active = TRUE,
-- automatically deactivate all other versions for
-- that user. Prevents stale active flags.
-- -----------------------------------------------------

CREATE OR REPLACE FUNCTION enforce_one_active_dna()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.is_active = TRUE THEN
        UPDATE learning_dna
        SET    is_active = FALSE
        WHERE  user_id = NEW.user_id
          AND  id      <> NEW.id
          AND  is_active = TRUE;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_one_active_dna
AFTER INSERT OR UPDATE OF is_active ON learning_dna
FOR EACH ROW
WHEN (NEW.is_active = TRUE)
EXECUTE FUNCTION enforce_one_active_dna();


-- =====================================================
-- 3. ASSESSMENT DOMAIN
-- =====================================================

-- -----------------------------------------------------
-- ASSESSMENTS
-- -----------------------------------------------------

CREATE TABLE assessments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    book_id UUID NOT NULL
        REFERENCES books(id)
        ON DELETE CASCADE,

    assessment_type assessment_type NOT NULL,

    status assessment_status NOT NULL DEFAULT 'DRAFT',

    started_at TIMESTAMPTZ,

    completed_at TIMESTAMPTZ,

    total_questions INTEGER,

    score_percentage NUMERIC(5,2),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_total_questions CHECK (total_questions IS NULL OR total_questions > 0),

    CONSTRAINT chk_score
        CHECK (score_percentage IS NULL
               OR (score_percentage >= 0 AND score_percentage <= 100)),

    CONSTRAINT chk_assessment_time
        CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at)
);

CREATE INDEX idx_assessments_user   ON assessments(user_id);
CREATE INDEX idx_assessments_book   ON assessments(book_id);
CREATE INDEX idx_assessments_status ON assessments(status);
CREATE INDEX idx_assessment_user_book ON assessments(user_id, book_id);

-- Partial index: in-progress assessments lookups are hot
CREATE INDEX idx_active_assessments
    ON assessments(user_id)
    WHERE status = 'IN_PROGRESS';

-- -----------------------------------------------------
-- ASSESSMENT RESPONSES
-- -----------------------------------------------------
-- One row per question answered in an assessment.
-- confidence_level before answer reveal = calibration signal
-- (confident-but-wrong → highest-value revision targets).
-- -----------------------------------------------------

CREATE TABLE assessment_responses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    assessment_id UUID NOT NULL
        REFERENCES assessments(id)
        ON DELETE CASCADE,

    concept_id UUID NOT NULL
        REFERENCES concepts(id)
        ON DELETE CASCADE,

    question_id UUID NOT NULL
        REFERENCES generated_questions(id)
        ON DELETE CASCADE,

    -- captured before correctness reveal
    confidence_level INTEGER,

    response JSONB NOT NULL,

    is_correct BOOLEAN NOT NULL,

    response_time_seconds INTEGER,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_confidence_response
        CHECK (confidence_level IS NULL
               OR (confidence_level >= 1 AND confidence_level <= 5)),

    CONSTRAINT chk_response_time
        CHECK (response_time_seconds IS NULL OR response_time_seconds >= 0)
);

CREATE INDEX idx_assessment_responses_assessment ON assessment_responses(assessment_id);
CREATE INDEX idx_assessment_responses_concept    ON assessment_responses(concept_id);
CREATE INDEX idx_assessment_responses_question   ON assessment_responses(question_id);
CREATE INDEX idx_assessment_responses_response   ON assessment_responses USING GIN(response);

-- Hot query: confident-but-wrong items for targeted revision
CREATE INDEX idx_assessment_responses_miss
    ON assessment_responses(concept_id)
    WHERE is_correct = FALSE;

-- -----------------------------------------------------
-- ASSESSMENT OUTCOMES
-- -----------------------------------------------------
-- Per-concept result after assessment completes.
-- Seeds concept_mastery and user_concept_state on first run.
-- -----------------------------------------------------

CREATE TABLE assessment_outcomes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    assessment_id UUID NOT NULL
        REFERENCES assessments(id)
        ON DELETE CASCADE,

    concept_id UUID NOT NULL
        REFERENCES concepts(id)
        ON DELETE CASCADE,

    mastery_estimate NUMERIC(5,4) NOT NULL,

    placement_state placement_state NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_mastery_estimate
        CHECK (mastery_estimate >= 0 AND mastery_estimate <= 1),

    CONSTRAINT uq_assessment_concept_outcome UNIQUE (assessment_id, concept_id)
);

CREATE INDEX idx_assessment_outcomes_assessment ON assessment_outcomes(assessment_id);
CREATE INDEX idx_assessment_outcomes_concept    ON assessment_outcomes(concept_id);


-- =====================================================
-- 4. LEARNING DOMAIN
-- =====================================================

-- -----------------------------------------------------
-- CURRICULUM PLANS
-- -----------------------------------------------------
-- Generated learning order for a user on a specific book.
-- latest version = most recent plan.
-- -----------------------------------------------------

CREATE TABLE curriculum_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    book_id UUID NOT NULL
        REFERENCES books(id)
        ON DELETE CASCADE,

    version INTEGER NOT NULL,

    -- ordered list of concept IDs + metadata
    curriculum_json JSONB NOT NULL,

    generated_from_assessment UUID
        REFERENCES assessments(id)
        ON DELETE SET NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_curriculum_version CHECK (version > 0),

    CONSTRAINT uq_curriculum_user_book_version UNIQUE (user_id, book_id, version)
);

CREATE INDEX idx_curriculum_user         ON curriculum_plans(user_id);
CREATE INDEX idx_curriculum_book         ON curriculum_plans(book_id);
CREATE INDEX idx_curriculum_json         ON curriculum_plans USING GIN(curriculum_json);
CREATE INDEX idx_curriculum_user_book_version
    ON curriculum_plans(user_id, book_id, version DESC);

-- -----------------------------------------------------
-- LESSON SESSIONS
-- -----------------------------------------------------
-- One session = one concept taught by Socratic tutor.
-- generated_content = the lesson content (grounded in chunks).
-- generation_metadata = model version, prompt version,
--   graph_version, generation_time (separate for clean queries).
-- -----------------------------------------------------

CREATE TABLE lesson_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    concept_id UUID NOT NULL
        REFERENCES concepts(id)
        ON DELETE CASCADE,

    curriculum_plan_id UUID
        REFERENCES curriculum_plans(id)
        ON DELETE SET NULL,

    status lesson_status NOT NULL DEFAULT 'NOT_STARTED',

    generated_content JSONB NOT NULL,

    generation_metadata JSONB,

    started_at TIMESTAMPTZ,

    completed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_lesson_time
        CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at)
);

CREATE INDEX idx_lesson_sessions_user    ON lesson_sessions(user_id);
CREATE INDEX idx_lesson_sessions_concept ON lesson_sessions(concept_id);
CREATE INDEX idx_lesson_sessions_status  ON lesson_sessions(status);
CREATE INDEX idx_lesson_sessions_content ON lesson_sessions USING GIN(generated_content);

CREATE INDEX idx_active_lesson_sessions
    ON lesson_sessions(user_id)
    WHERE status = 'IN_PROGRESS';

-- -----------------------------------------------------
-- TUTOR INTERACTIONS
-- -----------------------------------------------------
-- Immutable turn-by-turn Socratic conversation log.
-- turn_index preserves ordering for transcript replay.
-- user_asked questions stored in generated_questions
-- with source='USER_ASKED', linked via question_id.
-- -----------------------------------------------------

CREATE TABLE tutor_interactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    lesson_session_id UUID NOT NULL
        REFERENCES lesson_sessions(id)
        ON DELETE CASCADE,

    -- ordering within session (0-indexed)
    turn_index INTEGER NOT NULL,

    user_message TEXT NOT NULL,

    assistant_message TEXT NOT NULL,

    hint_level INTEGER NOT NULL DEFAULT 0,

    -- optional link if this turn triggered a question capture
    question_id UUID
        REFERENCES generated_questions(id)
        ON DELETE SET NULL,

    model_name VARCHAR(100),

    token_input_count INTEGER,

    token_output_count INTEGER,

    latency_ms INTEGER,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_session_turn UNIQUE (lesson_session_id, turn_index),

    CONSTRAINT chk_hint_level
        CHECK (hint_level >= 0 AND hint_level <= 4),

    CONSTRAINT chk_turn_index
        CHECK (turn_index >= 0),

    CONSTRAINT chk_input_tokens
        CHECK (token_input_count IS NULL OR token_input_count >= 0),

    CONSTRAINT chk_output_tokens
        CHECK (token_output_count IS NULL OR token_output_count >= 0),

    CONSTRAINT chk_latency
        CHECK (latency_ms IS NULL OR latency_ms >= 0)
);

CREATE INDEX idx_tutor_interactions_session ON tutor_interactions(lesson_session_id);
CREATE INDEX idx_tutor_interactions_created ON tutor_interactions(created_at);
CREATE INDEX idx_tutor_interactions_question ON tutor_interactions(question_id)
    WHERE question_id IS NOT NULL;


-- =====================================================
-- 5. MASTERY DOMAIN
-- =====================================================

-- -----------------------------------------------------
-- USER_CONCEPT_STATE
-- -----------------------------------------------------
-- PER-USER DAG OVERLAY. This is how the UI knows whether
-- to render a concept as locked, available, mastered, due.
-- Single row per (user_id, concept_id, graph_version).
-- Updated by:
--   - Assessment completion → seeds locked/available/mastered
--   - Lesson completion → transitions to mastered
--   - FSRS scheduler → transitions mastered → due
--   - Prerequisite check → transitions locked → available
-- -----------------------------------------------------

CREATE TABLE user_concept_state (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    concept_id UUID NOT NULL
        REFERENCES concepts(id)
        ON DELETE CASCADE,

    -- graph_version integer: matches the version in user_books.pinned_graph_version_id.
    -- Not a FK here (would require a join through graph_versions to validate),
    -- so kept as a bare integer. Application invariant: this value must equal
    -- graph_versions.version for the graph_version_id pinned in user_books.
    graph_version INTEGER NOT NULL,

    state node_state NOT NULL DEFAULT 'LOCKED',

    state_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_user_concept_state UNIQUE (user_id, concept_id, graph_version),

    CONSTRAINT chk_ucs_graph_version CHECK (graph_version > 0)
);

CREATE INDEX idx_ucs_user          ON user_concept_state(user_id);
CREATE INDEX idx_ucs_concept       ON user_concept_state(concept_id);
CREATE INDEX idx_ucs_state         ON user_concept_state(state);
CREATE INDEX idx_ucs_user_state    ON user_concept_state(user_id, state);

-- Hot: fetch all LOCKED nodes for a user to check prerequisites
CREATE INDEX idx_ucs_locked
    ON user_concept_state(user_id)
    WHERE state = 'LOCKED';

-- Hot: fetch all DUE nodes for daily revision plan
CREATE INDEX idx_ucs_due
    ON user_concept_state(user_id)
    WHERE state = 'DUE';

CREATE TRIGGER trg_ucs_updated_at
BEFORE UPDATE ON user_concept_state
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------
-- CONCEPT_MASTERY
-- -----------------------------------------------------
-- Source of truth for numeric mastery score per concept.
-- Exactly ONE row per (user_id, concept_id).
-- Drives curriculum generation and dashboard.
-- -----------------------------------------------------

CREATE TABLE concept_mastery (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    concept_id UUID NOT NULL
        REFERENCES concepts(id)
        ON DELETE CASCADE,

    mastery_score NUMERIC(5,4) NOT NULL DEFAULT 0,

    mastery_state mastery_state NOT NULL DEFAULT 'UNKNOWN',

    first_mastered_at TIMESTAMPTZ,

    last_reviewed_at TIMESTAMPTZ,

    updated_by_source review_source,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_user_concept_mastery UNIQUE (user_id, concept_id),

    CONSTRAINT chk_mastery_score
        CHECK (mastery_score >= 0 AND mastery_score <= 1),

    -- If state is MASTERED, first_mastered_at must be set
    CONSTRAINT chk_mastery_mastered_timestamp
        CHECK (mastery_state != 'MASTERED' OR first_mastered_at IS NOT NULL)
);

CREATE INDEX idx_concept_mastery_user       ON concept_mastery(user_id);
CREATE INDEX idx_concept_mastery_concept    ON concept_mastery(concept_id);
CREATE INDEX idx_concept_mastery_state      ON concept_mastery(mastery_state);
CREATE INDEX idx_concept_mastery_user_state ON concept_mastery(user_id, mastery_state);
CREATE INDEX idx_concept_mastery_score      ON concept_mastery(mastery_score);

CREATE INDEX idx_mastery_user_concept_score
    ON concept_mastery(user_id, concept_id, mastery_score);

CREATE TRIGGER trg_concept_mastery_updated_at
BEFORE UPDATE ON concept_mastery
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------
-- CONCEPT_FSRS
-- -----------------------------------------------------
-- Per-user FSRS-5 scheduling state. Exactly ONE row
-- per (user_id, concept_id). Initialized on first lesson
-- completion for a concept.
--
-- FSRS-5 parameter ranges:
--   stability:      > 0 (days until 90% retention)
--   difficulty:     1.0–10.0  (per FSRS-4.5/5 spec)
--   retrievability: 0.0–1.0   (current recall probability)
--   repetitions:    >= 0 (successful review count)
--   lapses:         >= 0 (forgotten count)
-- -----------------------------------------------------

CREATE TABLE concept_fsrs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    concept_id UUID NOT NULL
        REFERENCES concepts(id)
        ON DELETE CASCADE,

    -- Initial values per FSRS-5 default parameters
    stability      DOUBLE PRECISION NOT NULL DEFAULT 0.4,
    difficulty     DOUBLE PRECISION NOT NULL DEFAULT 5.0,
    retrievability DOUBLE PRECISION NOT NULL DEFAULT 1.0,

    repetitions INTEGER NOT NULL DEFAULT 0,

    lapses INTEGER NOT NULL DEFAULT 0,

    next_due TIMESTAMPTZ,

    last_reviewed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_user_concept_fsrs UNIQUE (user_id, concept_id),

    CONSTRAINT chk_stability       CHECK (stability >= 0),
    CONSTRAINT chk_difficulty      CHECK (difficulty >= 1 AND difficulty <= 10),
    CONSTRAINT chk_retrievability  CHECK (retrievability >= 0 AND retrievability <= 1),
    CONSTRAINT chk_repetitions     CHECK (repetitions >= 0),
    CONSTRAINT chk_lapses          CHECK (lapses >= 0)
);

CREATE INDEX idx_concept_fsrs_user    ON concept_fsrs(user_id);
CREATE INDEX idx_concept_fsrs_concept ON concept_fsrs(concept_id);

-- Composite index for the daily revision queue query:
-- WHERE user_id = $1 AND next_due <= NOW()
CREATE INDEX idx_concept_fsrs_due_user ON concept_fsrs(user_id, next_due);

-- Partial index — only rows with a scheduled review date
-- (skips concepts not yet started, avoids index bloat)
CREATE INDEX idx_due_reviews
    ON concept_fsrs(user_id, next_due)
    WHERE next_due IS NOT NULL;

CREATE TRIGGER trg_concept_fsrs_updated_at
BEFORE UPDATE ON concept_fsrs
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------
-- FSRS REVIEWS  (immutable event log)
-- -----------------------------------------------------
-- Every review event appends one row.
-- before/after captures the state delta for analytics
-- and debugging.
-- -----------------------------------------------------

CREATE TABLE fsrs_reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    concept_id UUID NOT NULL
        REFERENCES concepts(id)
        ON DELETE CASCADE,

    review_source review_source NOT NULL,

    -- FSRS grade: 1=Again, 2=Hard, 3=Good, 4=Easy
    review_grade INTEGER NOT NULL,

    stability_before      DOUBLE PRECISION,
    stability_after       DOUBLE PRECISION,
    difficulty_before     DOUBLE PRECISION,
    difficulty_after      DOUBLE PRECISION,
    retrievability_before DOUBLE PRECISION,
    retrievability_after  DOUBLE PRECISION,

    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_review_grade
        CHECK (review_grade >= 1 AND review_grade <= 4)
);

CREATE INDEX idx_fsrs_reviews_user         ON fsrs_reviews(user_id);
CREATE INDEX idx_fsrs_reviews_concept      ON fsrs_reviews(concept_id);
CREATE INDEX idx_fsrs_reviews_reviewed_at  ON fsrs_reviews(reviewed_at DESC);
CREATE INDEX idx_fsrs_reviews_user_concept ON fsrs_reviews(user_id, concept_id);

-- -----------------------------------------------------
-- MASTERY EVENTS  (audit trail for mastery changes)
-- -----------------------------------------------------
-- Every time mastery_score changes, append a row.
-- Invaluable for debugging, viva explanations, and
-- mastery evolution visualization on the dashboard.
-- -----------------------------------------------------

CREATE TABLE mastery_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    concept_id UUID NOT NULL
        REFERENCES concepts(id)
        ON DELETE CASCADE,

    source review_source NOT NULL,

    previous_mastery NUMERIC(5,4),

    new_mastery NUMERIC(5,4),

    reason TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_prev_mastery
        CHECK (previous_mastery IS NULL
               OR (previous_mastery >= 0 AND previous_mastery <= 1)),

    CONSTRAINT chk_new_mastery
        CHECK (new_mastery IS NULL
               OR (new_mastery >= 0 AND new_mastery <= 1))
);

CREATE INDEX idx_mastery_events_user    ON mastery_events(user_id);
CREATE INDEX idx_mastery_events_concept ON mastery_events(concept_id);
CREATE INDEX idx_mastery_events_created ON mastery_events(created_at DESC);


-- =====================================================
-- 6. GAMIFICATION DOMAIN
-- =====================================================

-- -----------------------------------------------------
-- CONTENT COMPLETIONS
-- -----------------------------------------------------
-- Idempotency guard: prevents awarding bonuses more than
-- once for the same (user, content, version) triple.
-- -----------------------------------------------------

CREATE TABLE content_completions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    content_type VARCHAR(50) NOT NULL,

    content_id UUID NOT NULL,

    content_version INTEGER NOT NULL,

    completed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_content_version CHECK (content_version > 0),

    CONSTRAINT uq_completion
        UNIQUE (user_id, content_type, content_id, content_version)
);

CREATE INDEX idx_content_completions_user    ON content_completions(user_id);
CREATE INDEX idx_content_completions_content ON content_completions(content_type, content_id);

-- -----------------------------------------------------
-- DAILY ACTIVITY
-- -----------------------------------------------------
-- One row per (user, date). Incremented by application
-- on each relevant action. Source of truth for streaks.
-- -----------------------------------------------------

CREATE TABLE daily_activity (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    activity_date DATE NOT NULL,

    minutes_studied INTEGER NOT NULL DEFAULT 0,

    concepts_learned INTEGER NOT NULL DEFAULT 0,

    concepts_reviewed INTEGER NOT NULL DEFAULT 0,

    lessons_completed INTEGER NOT NULL DEFAULT 0,

    assessments_completed INTEGER NOT NULL DEFAULT 0,

    questions_answered INTEGER NOT NULL DEFAULT 0,

    tutor_messages_sent INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_daily_activity UNIQUE (user_id, activity_date),

    CONSTRAINT chk_minutes_studied     CHECK (minutes_studied >= 0),
    CONSTRAINT chk_concepts_learned    CHECK (concepts_learned >= 0),
    CONSTRAINT chk_concepts_reviewed   CHECK (concepts_reviewed >= 0),
    CONSTRAINT chk_lessons_completed   CHECK (lessons_completed >= 0),
    CONSTRAINT chk_assessments_comp    CHECK (assessments_completed >= 0),
    CONSTRAINT chk_questions_answered  CHECK (questions_answered >= 0),
    CONSTRAINT chk_tutor_messages      CHECK (tutor_messages_sent >= 0)
);

CREATE INDEX idx_daily_activity_user      ON daily_activity(user_id);
CREATE INDEX idx_daily_activity_date      ON daily_activity(activity_date);
CREATE INDEX idx_daily_activity_user_date ON daily_activity(user_id, activity_date DESC);

-- -----------------------------------------------------
-- LEARNING STREAKS  (global daily streak)
-- -----------------------------------------------------
-- One row per user. Updated by streak recalculation
-- function after each daily_activity upsert.
-- -----------------------------------------------------

CREATE TABLE learning_streaks (
    user_id UUID PRIMARY KEY
        REFERENCES users(id)
        ON DELETE CASCADE,

    current_streak_days  INTEGER NOT NULL DEFAULT 0,

    longest_streak_days  INTEGER NOT NULL DEFAULT 0,

    last_activity_date   DATE,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_current_streak CHECK (current_streak_days >= 0),
    CONSTRAINT chk_longest_streak CHECK (longest_streak_days >= 0)
);

CREATE TRIGGER trg_learning_streaks_updated_at
BEFORE UPDATE ON learning_streaks
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------
-- BOOK STREAKS  (per-book consistency streak)
-- -----------------------------------------------------
-- Design doc: streaks at two levels — global daily streak
-- (learning_streaks) AND per-book consistency streak.
-- -----------------------------------------------------

CREATE TABLE book_streaks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    book_id UUID NOT NULL
        REFERENCES books(id)
        ON DELETE CASCADE,

    current_streak_days INTEGER NOT NULL DEFAULT 0,

    longest_streak_days INTEGER NOT NULL DEFAULT 0,

    last_activity_date DATE,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_book_streak UNIQUE (user_id, book_id),

    CONSTRAINT chk_book_current_streak CHECK (current_streak_days >= 0),
    CONSTRAINT chk_book_longest_streak CHECK (longest_streak_days >= 0)
);

CREATE INDEX idx_book_streaks_user ON book_streaks(user_id);
CREATE INDEX idx_book_streaks_book ON book_streaks(book_id);

CREATE TRIGGER trg_book_streaks_updated_at
BEFORE UPDATE ON book_streaks
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------
-- PROGRESS SNAPSHOTS
-- -----------------------------------------------------
-- Daily snapshot of per-book progress metrics.
-- Allows progress trend charts on the dashboard.
-- Populated by a scheduled job (not real-time).
-- -----------------------------------------------------

CREATE TABLE progress_snapshots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    book_id UUID NOT NULL
        REFERENCES books(id)
        ON DELETE CASCADE,

    mastered_concepts  INTEGER NOT NULL DEFAULT 0,

    learning_concepts  INTEGER NOT NULL DEFAULT 0,

    weak_concepts      INTEGER NOT NULL DEFAULT 0,

    total_concepts     INTEGER NOT NULL DEFAULT 0,

    overall_progress   NUMERIC(5,2) NOT NULL DEFAULT 0,

    average_mastery    NUMERIC(5,4),

    average_retrievability NUMERIC(5,4),

    snapshot_date DATE NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_snapshot UNIQUE (user_id, book_id, snapshot_date),

    CONSTRAINT chk_progress
        CHECK (overall_progress >= 0 AND overall_progress <= 100),

    CONSTRAINT chk_avg_mastery
        CHECK (average_mastery IS NULL
               OR (average_mastery >= 0 AND average_mastery <= 1)),

    CONSTRAINT chk_avg_retrievability
        CHECK (average_retrievability IS NULL
               OR (average_retrievability >= 0 AND average_retrievability <= 1))
);

CREATE INDEX idx_progress_snapshots_user ON progress_snapshots(user_id);
CREATE INDEX idx_progress_snapshots_book ON progress_snapshots(book_id);
CREATE INDEX idx_progress_snapshots_date ON progress_snapshots(snapshot_date DESC);
CREATE INDEX idx_progress_user_book      ON progress_snapshots(user_id, book_id);


-- =====================================================
-- 7. ANALYTICS  (Materialized Views + Helper Views)
-- =====================================================

-- -----------------------------------------------------
-- mv_revision_queue
-- -----------------------------------------------------
-- Hot dashboard query: "what should I revise today?"
-- Refresh: CONCURRENTLY requires a unique index on the MV.
-- Refresh strategy: after every FSRS review batch,
-- or on a cron (e.g., every 15 min).
-- -----------------------------------------------------

CREATE MATERIALIZED VIEW mv_revision_queue
WITH (fillfactor = 90)
AS
SELECT
    cf.user_id,
    cf.concept_id,
    c.name         AS concept_name,
    c.book_id,
    c.difficulty_level,
    cf.next_due,
    cf.retrievability,
    cf.stability,
    cf.difficulty,
    cf.repetitions,
    cf.lapses
FROM concept_fsrs cf
JOIN concepts c ON c.id = cf.concept_id
WHERE cf.next_due IS NOT NULL
WITH NO DATA;

-- Unique index required for REFRESH CONCURRENTLY
CREATE UNIQUE INDEX uq_mv_revision_queue
    ON mv_revision_queue(user_id, concept_id);

CREATE INDEX idx_mv_revision_queue_user ON mv_revision_queue(user_id);
CREATE INDEX idx_mv_revision_queue_due  ON mv_revision_queue(user_id, next_due);

-- -----------------------------------------------------
-- mv_user_book_progress
-- -----------------------------------------------------

CREATE MATERIALIZED VIEW mv_user_book_progress
WITH (fillfactor = 90)
AS
SELECT
    cm.user_id,
    c.book_id,
    COUNT(*)                                              AS total_concepts,
    COUNT(*) FILTER (WHERE cm.mastery_state = 'MASTERED') AS mastered_concepts,
    COUNT(*) FILTER (WHERE cm.mastery_state = 'LEARNING') AS learning_concepts,
    COUNT(*) FILTER (WHERE cm.mastery_state = 'FORGOTTEN') AS forgotten_concepts,
    ROUND(AVG(cm.mastery_score)::numeric, 4)              AS average_mastery
FROM concept_mastery cm
JOIN concepts c ON c.id = cm.concept_id
GROUP BY cm.user_id, c.book_id
WITH NO DATA;

CREATE UNIQUE INDEX uq_mv_user_book_progress
    ON mv_user_book_progress(user_id, book_id);

CREATE INDEX idx_mv_user_book_progress
    ON mv_user_book_progress(user_id, book_id);

-- -----------------------------------------------------
-- mv_concept_performance
-- -----------------------------------------------------

CREATE MATERIALIZED VIEW mv_concept_performance
WITH (fillfactor = 90)
AS
SELECT
    ar.concept_id,
    COUNT(*)                                              AS attempts,
    ROUND(AVG(CASE WHEN ar.is_correct THEN 1 ELSE 0 END)::numeric, 4) AS accuracy_rate,
    ROUND(AVG(ar.confidence_level)::numeric, 2)          AS average_confidence,
    COUNT(*) FILTER (WHERE ar.is_correct = FALSE
                     AND ar.confidence_level >= 4)        AS confident_wrong_count
FROM assessment_responses ar
GROUP BY ar.concept_id
WITH NO DATA;

CREATE UNIQUE INDEX uq_mv_concept_performance
    ON mv_concept_performance(concept_id);

CREATE INDEX idx_mv_concept_performance_concept
    ON mv_concept_performance(concept_id);

-- -----------------------------------------------------
-- Helper Views (live queries — no refresh needed)
-- -----------------------------------------------------

CREATE VIEW v_user_revision_tasks AS
SELECT
    cf.user_id,
    cf.concept_id,
    c.name,
    c.book_id,
    cf.next_due,
    cf.retrievability,
    cf.stability,
    cf.lapses
FROM concept_fsrs cf
JOIN concepts c ON c.id = cf.concept_id
WHERE cf.next_due IS NOT NULL
ORDER BY cf.next_due ASC;

CREATE VIEW v_user_mastery_summary AS
SELECT
    user_id,
    COUNT(*)                                              AS total_concepts,
    COUNT(*) FILTER (WHERE mastery_state = 'MASTERED')   AS mastered,
    COUNT(*) FILTER (WHERE mastery_state = 'LEARNING')   AS learning,
    COUNT(*) FILTER (WHERE mastery_state = 'FORGOTTEN')  AS forgotten,
    ROUND(AVG(mastery_score)::numeric, 4)                AS avg_mastery
FROM concept_mastery
GROUP BY user_id;

CREATE VIEW v_book_progress AS
SELECT
    cm.user_id,
    c.book_id,
    COUNT(*)                                              AS total_concepts,
    COUNT(*) FILTER (WHERE cm.mastery_state = 'MASTERED') AS mastered_concepts,
    ROUND(
        COUNT(*) FILTER (WHERE cm.mastery_state = 'MASTERED')::numeric
        / NULLIF(COUNT(*), 0) * 100,
        2
    )                                                     AS progress_percent
FROM concept_mastery cm
JOIN concepts c ON c.id = cm.concept_id
GROUP BY cm.user_id, c.book_id;

-- DAG prerequisite view: for a given concept, list what unlocks it
CREATE VIEW v_concept_prerequisites AS
SELECT
    e.to_concept_id   AS concept_id,
    e.from_concept_id AS prerequisite_id,
    p.name            AS prerequisite_name,
    e.confidence,
    e.is_verified
FROM concept_edges e
JOIN concepts p ON p.id = e.from_concept_id
WHERE e.edge_type = 'PREREQUISITE';


-- =====================================================
-- 8. PRODUCTION LAYER
-- =====================================================

-- -----------------------------------------------------
-- MATERIALIZED VIEW REFRESH FUNCTIONS
-- Use CONCURRENTLY to avoid locking during refresh.
-- Caller must ensure the MV has been populated first
-- (REFRESH without CONCURRENTLY on first run).
-- -----------------------------------------------------

CREATE OR REPLACE FUNCTION refresh_revision_queue()
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_revision_queue;
END;
$$;

CREATE OR REPLACE FUNCTION refresh_user_progress()
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_user_book_progress;
END;
$$;

CREATE OR REPLACE FUNCTION refresh_concept_performance()
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_concept_performance;
END;
$$;

-- -----------------------------------------------------
-- STREAK CALCULATION FUNCTION
-- -----------------------------------------------------
-- Correctly computes consecutive-day streak from
-- daily_activity, not just a row count.
-- Returns current streak length.
-- -----------------------------------------------------

CREATE OR REPLACE FUNCTION calculate_current_streak(p_user_id UUID)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
-- Algorithm:
--   Walk activity_date DESC from the most recent day.
--   A streak is consecutive if each row is exactly 1 day
--   before the previous one we accepted.
--
--   Edge cases handled:
--   1. No activity today — start from yesterday (streak still
--      valid if user studied yesterday and before).
--   2. Gap in the middle — stop immediately on any break.
--   3. Duplicate dates prevented by UNIQUE constraint.
--
-- Implementation note: calculate_current_streak() is a DB
-- convenience. The canonical streak value is stored in
-- learning_streaks.current_streak_days and is the source
-- of truth for the dashboard. This function is used only
-- to recompute it when a daily_activity row is upserted.
DECLARE
    streak      INTEGER := 0;
    check_date  DATE    := CURRENT_DATE;
    prev_date   DATE    := NULL;
    rec         RECORD;
BEGIN
    SELECT MAX(activity_date)
    INTO   prev_date
    FROM   daily_activity
    WHERE  user_id = p_user_id;

    -- No activity at all
    IF prev_date IS NULL THEN
        RETURN 0;
    END IF;

    -- Most recent activity is older than yesterday: streak already broken
    IF prev_date < CURRENT_DATE - INTERVAL '1 day' THEN
        RETURN 0;
    END IF;

    -- Walk backwards counting consecutive days
    FOR rec IN (
        SELECT activity_date
        FROM   daily_activity
        WHERE  user_id = p_user_id
          AND  activity_date <= CURRENT_DATE
        ORDER  BY activity_date DESC
    )
    LOOP
        IF streak = 0 THEN
            -- First row: must be today or yesterday to start streak
            IF rec.activity_date >= CURRENT_DATE - INTERVAL '1 day' THEN
                streak     := 1;
                check_date := rec.activity_date;
            ELSE
                EXIT;  -- first ever activity is older than yesterday
            END IF;
        ELSIF rec.activity_date = check_date - INTERVAL '1 day' THEN
            streak     := streak + 1;
            check_date := rec.activity_date;
        ELSE
            EXIT;  -- gap found — stop
        END IF;
    END LOOP;

    RETURN streak;
END;
$$;

-- -----------------------------------------------------
-- AUTO-UPDATE search_vector TRIGGER ON concepts
-- -----------------------------------------------------
-- Keeps tsvector in sync whenever name or summary changes.
-- Uses 'english' dictionary; adjust for other locales.
-- -----------------------------------------------------

CREATE OR REPLACE FUNCTION concepts_search_vector_update()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.search_vector :=
        setweight(to_tsvector('english', COALESCE(NEW.name, '')),    'A') ||
        setweight(to_tsvector('english', COALESCE(NEW.summary, '')), 'B') ||
        setweight(to_tsvector('english', COALESCE(NEW.learning_objective, '')), 'C');
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_concepts_search_vector
BEFORE INSERT OR UPDATE OF name, summary, learning_objective
ON concepts
FOR EACH ROW EXECUTE FUNCTION concepts_search_vector_update();

-- =====================================================
-- TABLE COMMENTS
-- =====================================================

COMMENT ON TABLE books               IS 'Uploaded books and learning resources. Status lifecycle: UPLOADING→PARSING→EXTRACTING_CONCEPTS→KG_BUILT→KG_VERIFIED→READY.';
COMMENT ON TABLE chapters            IS 'Book chapters. Structural prior for concept extraction and chunking.';
COMMENT ON TABLE source_chunks       IS 'Text chunks from books. Every concept is traceable back to its source chunks.';
COMMENT ON TABLE concepts            IS 'KG nodes — canonical concepts extracted from books per graph version.';
COMMENT ON TABLE concept_edges       IS 'KG edges — prerequisite/related links between concepts forming a DAG. DAG invariant enforced at pipeline layer.';
COMMENT ON TABLE concept_chunks      IS 'Many-to-many: concept ↔ source chunks used to ground it.';
COMMENT ON TABLE generated_questions IS 'Questions per concept. source=USER_ASKED|ASSESSMENT_MISS powers targeted revision.';
COMMENT ON TABLE graph_build_jobs    IS 'Async pipeline job tracker. Only one COMPLETED build per (book, graph_version).';
COMMENT ON TABLE users               IS 'Platform users.';
COMMENT ON TABLE user_books          IS 'User enrollment in a book. Pins graph version at enrollment time.';
COMMENT ON TABLE learner_profiles    IS 'Learner preferences and initial calibration.';
COMMENT ON TABLE learning_dna        IS 'Versioned personalized learner model. Append-only.';
COMMENT ON TABLE assessments         IS 'Placement/chapter/revision assessments per user per book.';
COMMENT ON TABLE assessment_responses IS 'Per-question responses. confidence_level before reveal = calibration signal.';
COMMENT ON TABLE assessment_outcomes  IS 'Per-concept placement result seeding mastery and node_state.';
COMMENT ON TABLE curriculum_plans    IS 'Generated learning order for a user on a book.';
COMMENT ON TABLE lesson_sessions     IS 'One session = Socratic teaching of one concept.';
COMMENT ON TABLE tutor_interactions  IS 'Immutable turn-by-turn Socratic conversation log with turn_index ordering.';
COMMENT ON TABLE user_concept_state  IS 'DAG overlay per user: LOCKED|AVAILABLE|IN_PROGRESS|MASTERED|DUE. Drives graph reveal UI.';
COMMENT ON TABLE concept_mastery     IS 'Source of truth for numeric mastery score per (user, concept).';
COMMENT ON TABLE concept_fsrs        IS 'FSRS-5 scheduling state per (user, concept). Initialized on first lesson completion.';
COMMENT ON TABLE fsrs_reviews        IS 'Immutable FSRS review event log with before/after state delta.';
COMMENT ON TABLE mastery_events      IS 'Audit trail for every mastery_score change. Useful for visualization and debugging.';
COMMENT ON TABLE content_completions IS 'Idempotency guard for bonus awards. First completion wins.';
COMMENT ON TABLE daily_activity      IS 'One row per (user, date). Source of truth for streak computation.';
COMMENT ON TABLE learning_streaks    IS 'Global daily-activity streak per user.';
COMMENT ON TABLE book_streaks        IS 'Per-book consistency streak per user.';
COMMENT ON TABLE progress_snapshots  IS 'Daily snapshot of per-book progress metrics for trend charts.';
COMMENT ON TABLE graph_versions      IS 'Named snapshot of each completed graph build per book. Single source for version lookups.';

-- =====================================================
-- SCHEMA COMPLETE
-- =====================================================
-- Tables:
--   Content: books, chapters, source_chunks, concepts,
--            concept_edges, concept_chunks,
--            generated_questions, graph_build_jobs,
--            graph_versions                             (9)
--   User:    users, user_books, learner_profiles,
--            learning_dna                               (4)
--   Assessment: assessments, assessment_responses,
--               assessment_outcomes                     (3)
--   Learning: curriculum_plans, lesson_sessions,
--             tutor_interactions                        (3)
--   Mastery:  user_concept_state, concept_mastery,
--             concept_fsrs, fsrs_reviews,
--             mastery_events                            (5)
--   Gamification: content_completions, daily_activity,
--                 learning_streaks, book_streaks,
--                 progress_snapshots                    (5)
--
--   TOTAL: 29 tables
--
-- Materialized Views: mv_revision_queue,
--   mv_user_book_progress, mv_concept_performance      (3)
--
-- Views: v_user_revision_tasks, v_user_mastery_summary,
--        v_book_progress, v_concept_prerequisites      (4)
-- =====================================================

-- =====================================================
-- 9. NOTIFICATIONS DOMAIN
-- =====================================================

CREATE TYPE notification_type AS ENUM (
    'REVISION_DUE',
    'STREAK_WARNING',
    'GRAPH_BUILT',
    'SYSTEM_ALERT'
);

CREATE TABLE notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type notification_type NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    action_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_notifications_user ON notifications(user_id);
CREATE INDEX idx_notifications_unread ON notifications(user_id) WHERE is_read = FALSE;

