"""add canonical_concept_id lineage to raw_concepts

Revision ID: 0ead7cbfca32
Revises: 1d94996364e1
Create Date: 2026-06-09 21:06:30.397242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ead7cbfca32'
down_revision: Union[str, Sequence[str], None] = '1d94996364e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_concepts', sa.Column('canonical_concept_id', sa.UUID(), nullable=True))
    op.add_column('raw_concepts', sa.Column('canonicalized_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'raw_concepts', 'concepts', ['canonical_concept_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw_concepts', type_='foreignkey')
    op.drop_column('raw_concepts', 'canonicalized_at')
    op.drop_column('raw_concepts', 'canonical_concept_id')
    # ### end Alembic commands ###
