"""create_daily_plans_and_audit

Revision ID: 1b49dcbe9dc0
Revises: de54f380a89e
Create Date: 2026-06-07 22:47:48.017951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b49dcbe9dc0'
down_revision: Union[str, Sequence[str], None] = 'de54f380a89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('learn_concept_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_version_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['graph_version_id'], ['graph_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_version_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_version_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['graph_version_id'], ['graph_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_books_created_at'), table_name='books')
    op.create_index('idx_books_created_at', 'books', ['created_at'], unique=False)
    op.create_foreign_key(None, 'books', 'users', ['owner_id'], ['id'])
    op.create_table_comment(
        'books',
        'Uploaded books and learning resources. Status lifecycle: UPLOADINGΓåÆPARSINGΓåÆEXTRACTING_CONCEPTSΓåÆKG_BUILTΓåÆKG_VERIFIEDΓåÆREADY.',
        existing_comment='Uploaded books and learning resources. Status lifecycle: UPLOADING→PARSING→EXTRACTING_CONCEPTS→KG_BUILT→KG_VERIFIED→READY.',
        schema=None
    )
    op.create_table_comment(
        'concept_chunks',
        'Many-to-many: concept Γåö source chunks used to ground it.',
        existing_comment='Many-to-many: concept ↔ source chunks used to ground it.',
        schema=None
    )
    op.create_table_comment(
        'concept_edges',
        'KG edges ΓÇö prerequisite/related links between concepts forming a DAG. DAG invariant enforced at pipeline layer.',
        existing_comment='KG edges — prerequisite/related links between concepts forming a DAG. DAG invariant enforced at pipeline layer.',
        schema=None
    )
    op.drop_index(op.f('idx_concept_fsrs_concept'), table_name='concept_fsrs')
    op.drop_index(op.f('idx_concept_fsrs_due_user'), table_name='concept_fsrs')
    op.drop_index(op.f('idx_concept_fsrs_user'), table_name='concept_fsrs')
    op.drop_index(op.f('idx_due_reviews'), table_name='concept_fsrs', postgresql_where='(next_due IS NOT NULL)')
    op.drop_constraint(op.f('uq_user_concept_fsrs'), 'concept_fsrs', type_='unique')
    op.drop_table_comment(
        'concept_fsrs',
        existing_comment='FSRS-5 scheduling state per (user, concept). Initialized on first lesson completion.',
        schema=None
    )
    op.create_table_comment(
        'concepts',
        'KG nodes ΓÇö canonical concepts extracted from books per graph version.',
        existing_comment='KG nodes — canonical concepts extracted from books per graph version.',
        schema=None
    )
    op.drop_index(op.f('idx_curriculum_user_book_version'), table_name='curriculum_plans')
    op.create_index('idx_curriculum_user_book_version', 'curriculum_plans', ['user_id', 'book_id', 'version'], unique=False)
    op.drop_index(op.f('idx_daily_activity_user_date'), table_name='daily_activity')
    op.create_index('idx_daily_activity_user_date', 'daily_activity', ['user_id', 'activity_date'], unique=False)
    op.drop_index(op.f('idx_fsrs_reviews_concept'), table_name='fsrs_reviews')
    op.drop_index(op.f('idx_fsrs_reviews_reviewed_at'), table_name='fsrs_reviews')
    op.drop_index(op.f('idx_fsrs_reviews_user'), table_name='fsrs_reviews')
    op.drop_index(op.f('idx_fsrs_reviews_user_concept'), table_name='fsrs_reviews')
    op.drop_table_comment(
        'fsrs_reviews',
        existing_comment='Immutable FSRS review event log with before/after state delta.',
        schema=None
    )
    op.alter_column('graph_versions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table_comment(
        'learner_profiles',
        existing_comment='Learner preferences and initial calibration.',
        schema=None
    )
    op.drop_index(op.f('idx_mastery_events_created'), table_name='mastery_events')
    op.create_index('idx_mastery_events_created', 'mastery_events', ['created_at'], unique=False)
    op.drop_index(op.f('idx_progress_snapshots_date'), table_name='progress_snapshots')
    op.create_index('idx_progress_snapshots_date', 'progress_snapshots', ['snapshot_date'], unique=False)
    op.alter_column('user_books', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'user_books', 'chapters', ['current_chapter_id'], ['id'])
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'avatar_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'user_books', type_='foreignkey')
    op.alter_column('user_books', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_progress_snapshots_date', table_name='progress_snapshots')
    op.create_index(op.f('idx_progress_snapshots_date'), 'progress_snapshots', [sa.literal_column('snapshot_date DESC')], unique=False)
    op.drop_index('idx_mastery_events_created', table_name='mastery_events')
    op.create_index(op.f('idx_mastery_events_created'), 'mastery_events', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table_comment(
        'learner_profiles',
        'Learner preferences and initial calibration.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('graph_versions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'fsrs_reviews',
        'Immutable FSRS review event log with before/after state delta.',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_fsrs_reviews_user_concept'), 'fsrs_reviews', ['user_id', 'concept_id'], unique=False)
    op.create_index(op.f('idx_fsrs_reviews_user'), 'fsrs_reviews', ['user_id'], unique=False)
    op.create_index(op.f('idx_fsrs_reviews_reviewed_at'), 'fsrs_reviews', [sa.literal_column('reviewed_at DESC')], unique=False)
    op.create_index(op.f('idx_fsrs_reviews_concept'), 'fsrs_reviews', ['concept_id'], unique=False)
    op.drop_index('idx_daily_activity_user_date', table_name='daily_activity')
    op.create_index(op.f('idx_daily_activity_user_date'), 'daily_activity', ['user_id', sa.literal_column('activity_date DESC')], unique=False)
    op.drop_index('idx_curriculum_user_book_version', table_name='curriculum_plans')
    op.create_index(op.f('idx_curriculum_user_book_version'), 'curriculum_plans', ['user_id', 'book_id', sa.literal_column('version DESC')], unique=False)
    op.create_table_comment(
        'concepts',
        'KG nodes — canonical concepts extracted from books per graph version.',
        existing_comment='KG nodes ΓÇö canonical concepts extracted from books per graph version.',
        schema=None
    )
    op.create_table_comment(
        'concept_fsrs',
        'FSRS-5 scheduling state per (user, concept). Initialized on first lesson completion.',
        existing_comment=None,
        schema=None
    )
    op.create_unique_constraint(op.f('uq_user_concept_fsrs'), 'concept_fsrs', ['user_id', 'concept_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_due_reviews'), 'concept_fsrs', ['user_id', 'next_due'], unique=False, postgresql_where='(next_due IS NOT NULL)')
    op.create_index(op.f('idx_concept_fsrs_user'), 'concept_fsrs', ['user_id'], unique=False)
    op.create_index(op.f('idx_concept_fsrs_due_user'), 'concept_fsrs', ['user_id', 'next_due'], unique=False)
    op.create_index(op.f('idx_concept_fsrs_concept'), 'concept_fsrs', ['concept_id'], unique=False)
    op.create_table_comment(
        'concept_edges',
        'KG edges — prerequisite/related links between concepts forming a DAG. DAG invariant enforced at pipeline layer.',
        existing_comment='KG edges ΓÇö prerequisite/related links between concepts forming a DAG. DAG invariant enforced at pipeline layer.',
        schema=None
    )
    op.create_table_comment(
        'concept_chunks',
        'Many-to-many: concept ↔ source chunks used to ground it.',
        existing_comment='Many-to-many: concept Γåö source chunks used to ground it.',
        schema=None
    )
    op.create_table_comment(
        'books',
        'Uploaded books and learning resources. Status lifecycle: UPLOADING→PARSING→EXTRACTING_CONCEPTS→KG_BUILT→KG_VERIFIED→READY.',
        existing_comment='Uploaded books and learning resources. Status lifecycle: UPLOADINGΓåÆPARSINGΓåÆEXTRACTING_CONCEPTSΓåÆKG_BUILTΓåÆKG_VERIFIEDΓåÆREADY.',
        schema=None
    )
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index('idx_books_created_at', table_name='books')
    op.create_index(op.f('idx_books_created_at'), 'books', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_table('graph_version_events')
    op.drop_table('graph_audit_events')
    op.drop_table('daily_plans')
    # ### end Alembic commands ###
