"""Add retention_score

Revision ID: 1d94996364e1
Revises: 1b49dcbe9dc0
Create Date: 2026-06-09 07:52:50.954425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d94996364e1'
down_revision: Union[str, Sequence[str], None] = '1b49dcbe9dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concept_mastery', sa.Column('retention_score', sa.Numeric(precision=5, scale=4), nullable=False))
    op.drop_index(op.f('idx_concepts_canonical'), table_name='concepts')
    op.drop_constraint(op.f('concepts_canonical_concept_id_fkey'), 'concepts', type_='foreignkey')
    op.drop_column('concepts', 'canonical_concept_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('canonical_concept_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('concepts_canonical_concept_id_fkey'), 'concepts', 'concepts', ['canonical_concept_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_concepts_canonical'), 'concepts', ['canonical_concept_id'], unique=False)
    op.drop_column('concept_mastery', 'retention_score')
    # ### end Alembic commands ###
