"""Initial schema

Revision ID: 5b1e5073d1f6
Revises: 
Create Date: 2026-06-17 21:32:23.042261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b1e5073d1f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('STUDENT', 'TEACHER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('daily_new_node_cap', sa.Integer(), nullable=False),
    sa.Column('daily_reminder_time', sa.String(length=5), nullable=True),
    sa.Column('session_length_pref', sa.Integer(), nullable=False),
    sa.Column('notify_reminders', sa.Boolean(), nullable=False),
    sa.Column('notify_due_reviews', sa.Boolean(), nullable=False),
    sa.Column('notify_processing', sa.Boolean(), nullable=False),
    sa.Column('global_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    comment='Platform users.'
    )
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('UPLOADING', 'PARSING', 'EXTRACTING_CONCEPTS', 'KG_BUILT', 'KG_VERIFIED', 'READY', name='book_status'), nullable=False),
    sa.Column('visibility', postgresql.ENUM('PRIVATE', 'PUBLIC', name='book_visibility'), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type::text = ANY (ARRAY['PDF'::character varying, 'EPUB'::character varying, 'TXT'::character varying, 'DOCX'::character varying, 'URL'::character varying]::text[])", name='books_source_type_check'),
    sa.CheckConstraint('page_count IS NULL OR page_count > 0', name='chk_page_count'),
    sa.CheckConstraint('processing_completed_at IS NULL OR processing_started_at IS NULL OR processing_completed_at >= processing_started_at', name='chk_processing_time'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_books_owner', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='books_pkey'),
    comment='Uploaded books and learning resources. Status lifecycle: UPLOADINGΓåÆPARSINGΓåÆEXTRACTING_CONCEPTSΓåÆKG_BUILTΓåÆKG_VERIFIEDΓåÆREADY.'
    )
    op.create_index('idx_books_created_at', 'books', ['created_at'], unique=False)
    op.create_index('idx_books_owner', 'books', ['owner_id'], unique=False)
    op.create_index('idx_books_status', 'books', ['status'], unique=False)
    op.create_index('idx_books_title', 'books', ['title'], unique=False)
    op.create_index('idx_books_visibility', 'books', ['visibility'], unique=False)
    op.create_table('content_completions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('content_version', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('content_version > 0', name='chk_content_version'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='content_completions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='content_completions_pkey'),
    sa.UniqueConstraint('user_id', 'content_type', 'content_id', 'content_version', name='uq_completion'),
    comment='Idempotency guard for bonus awards. First completion wins.'
    )
    op.create_index('idx_content_completions_content', 'content_completions', ['content_type', 'content_id'], unique=False)
    op.create_index('idx_content_completions_user', 'content_completions', ['user_id'], unique=False)
    op.create_table('daily_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('minutes_studied', sa.Integer(), nullable=False),
    sa.Column('tutor_messages_sent', sa.Integer(), nullable=False),
    sa.Column('lessons_completed', sa.Integer(), nullable=False),
    sa.Column('assessments_completed', sa.Integer(), nullable=False),
    sa.Column('concepts_learned', sa.Integer(), nullable=False),
    sa.Column('questions_answered', sa.Integer(), nullable=False),
    sa.Column('concepts_reviewed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('assessments_completed >= 0', name='chk_assessments_comp'),
    sa.CheckConstraint('concepts_learned >= 0', name='chk_concepts_learned'),
    sa.CheckConstraint('concepts_reviewed >= 0', name='chk_concepts_reviewed'),
    sa.CheckConstraint('lessons_completed >= 0', name='chk_lessons_completed'),
    sa.CheckConstraint('minutes_studied >= 0', name='chk_minutes_studied'),
    sa.CheckConstraint('questions_answered >= 0', name='chk_questions_answered'),
    sa.CheckConstraint('tutor_messages_sent >= 0', name='chk_tutor_messages'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='daily_activity_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='daily_activity_pkey'),
    sa.UniqueConstraint('user_id', 'activity_date', name='uq_daily_activity'),
    comment='One row per (user, date). Source of truth for streak computation.'
    )
    op.create_index('idx_daily_activity_date', 'daily_activity', ['activity_date'], unique=False)
    op.create_index('idx_daily_activity_user', 'daily_activity', ['user_id'], unique=False)
    op.create_index('idx_daily_activity_user_date', 'daily_activity', ['user_id', 'activity_date'], unique=False)
    op.create_table('learner_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('confidence_level', sa.Integer(), nullable=True),
    sa.Column('experience_level', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='experience_level'), nullable=True),
    sa.Column('preferred_examples', sa.String(length=100), nullable=True),
    sa.Column('learning_velocity', sa.String(length=20), nullable=True),
    sa.Column('preferred_study_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('learning_dna',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dna_version', sa.Integer(), nullable=False),
    sa.Column('dna_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dna_version > 0', name='chk_dna_version'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='learning_dna_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='learning_dna_pkey'),
    sa.UniqueConstraint('user_id', 'dna_version', name='uq_user_dna_version'),
    comment='Versioned personalized learner model. Append-only.'
    )
    op.create_index('idx_learning_dna_data', 'learning_dna', ['dna_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_learning_dna_user', 'learning_dna', ['user_id'], unique=False)
    op.create_index('uq_active_dna_per_user', 'learning_dna', ['user_id'], unique=True, postgresql_where='(is_active = true)')
    op.create_table('learning_streaks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_streak_days', sa.Integer(), nullable=False),
    sa.Column('longest_streak_days', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_streak_days >= 0', name='chk_current_streak'),
    sa.CheckConstraint('longest_streak_days >= 0', name='chk_longest_streak'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='learning_streaks_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name='learning_streaks_pkey'),
    comment='Global daily-activity streak per user.'
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('STREAK_WARNING', 'STREAK_LOST', 'STREAK_MILESTONE', 'MASTERY_MILESTONE', 'SYSTEM', name='notification_type'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('idx_notifications_unread', 'notifications', ['user_id'], unique=False, postgresql_where='(is_read = false)')
    op.create_index('idx_notifications_user', 'notifications', ['user_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('assessment_type', postgresql.ENUM('INITIAL', 'PLACEMENT', 'CHAPTER', 'REVISION', name='assessment_type'), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='assessment_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('score_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name='chk_assessment_time'),
    sa.CheckConstraint('score_percentage IS NULL OR score_percentage >= 0::numeric AND score_percentage <= 100::numeric', name='chk_score'),
    sa.CheckConstraint('total_questions IS NULL OR total_questions > 0', name='chk_total_questions'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='assessments_book_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='assessments_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='assessments_pkey'),
    comment='Placement/chapter/revision assessments per user per book.'
    )
    op.create_index('idx_active_assessments', 'assessments', ['user_id'], unique=False, postgresql_where="(status = 'IN_PROGRESS'::assessment_status)")
    op.create_index('idx_assessment_user_book', 'assessments', ['user_id', 'book_id'], unique=False)
    op.create_index('idx_assessments_book', 'assessments', ['book_id'], unique=False)
    op.create_index('idx_assessments_status', 'assessments', ['status'], unique=False)
    op.create_index('idx_assessments_user', 'assessments', ['user_id'], unique=False)
    op.create_table('book_streaks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('current_streak_days', sa.Integer(), nullable=False),
    sa.Column('longest_streak_days', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_streak_days >= 0', name='chk_book_current_streak'),
    sa.CheckConstraint('longest_streak_days >= 0', name='chk_book_longest_streak'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='book_streaks_book_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='book_streaks_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='book_streaks_pkey'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_book_streak'),
    comment='Per-book consistency streak per user.'
    )
    op.create_index('idx_book_streaks_book', 'book_streaks', ['book_id'], unique=False)
    op.create_index('idx_book_streaks_user', 'book_streaks', ['user_id'], unique=False)
    op.create_table('book_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('upload_status', postgresql.ENUM('PENDING', 'STORED', 'FAILED', name='upload_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='book_uploads_book_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='book_uploads_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='book_uploads_pkey')
    )
    op.create_table('chapters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chapter_number > 0', name='chk_chapter_number'),
    sa.CheckConstraint('estimated_minutes IS NULL OR estimated_minutes > 0', name='chk_estimated_minutes'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='chapters_book_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chapters_pkey'),
    sa.UniqueConstraint('book_id', 'chapter_number', name='uq_book_chapter_number'),
    comment='Book chapters. Structural prior for concept extraction and chunking.'
    )
    op.create_index('idx_chapters_book_id', 'chapters', ['book_id'], unique=False)
    op.create_index('idx_chapters_number', 'chapters', ['book_id', 'chapter_number'], unique=False)
    op.create_table('daily_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('learn_concept_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_concepts', sa.Integer(), nullable=False),
    sa.Column('learning_concepts', sa.Integer(), nullable=False),
    sa.Column('mastered_concepts', sa.Integer(), nullable=False),
    sa.Column('weak_concepts', sa.Integer(), nullable=False),
    sa.Column('average_mastery', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('average_retrievability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('overall_progress', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('average_mastery IS NULL OR average_mastery >= 0::numeric AND average_mastery <= 1::numeric', name='chk_avg_mastery'),
    sa.CheckConstraint('average_retrievability IS NULL OR average_retrievability >= 0::numeric AND average_retrievability <= 1::numeric', name='chk_avg_retrievability'),
    sa.CheckConstraint('overall_progress >= 0::numeric AND overall_progress <= 100::numeric', name='chk_progress'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='progress_snapshots_book_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='progress_snapshots_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='progress_snapshots_pkey'),
    sa.UniqueConstraint('user_id', 'book_id', 'snapshot_date', name='uq_snapshot'),
    comment='Daily snapshot of per-book progress metrics for trend charts.'
    )
    op.create_index('idx_progress_snapshots_book', 'progress_snapshots', ['book_id'], unique=False)
    op.create_index('idx_progress_snapshots_date', 'progress_snapshots', ['snapshot_date'], unique=False)
    op.create_index('idx_progress_snapshots_user', 'progress_snapshots', ['user_id'], unique=False)
    op.create_index('idx_progress_user_book', 'progress_snapshots', ['user_id', 'book_id'], unique=False)
    op.create_table('concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('learning_objective', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('graph_version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('difficulty_level >= 1 AND difficulty_level <= 5', name='chk_concept_difficulty'),
    sa.CheckConstraint('estimated_minutes IS NULL OR estimated_minutes > 0', name='chk_concept_minutes'),
    sa.CheckConstraint('graph_version > 0', name='chk_concept_graph_version'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='concepts_book_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name='concepts_chapter_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='concepts_pkey'),
    sa.UniqueConstraint('book_id', 'name', 'graph_version', name='uq_concept_book_name_version'),
    comment='KG nodes ΓÇö canonical concepts extracted from books per graph version.'
    )
    op.create_index('idx_concepts_book', 'concepts', ['book_id'], unique=False)
    op.create_index('idx_concepts_chapter', 'concepts', ['chapter_id'], unique=False)
    op.create_index('idx_concepts_difficulty', 'concepts', ['difficulty_level'], unique=False)
    op.create_index('idx_concepts_graph_version', 'concepts', ['book_id', 'graph_version'], unique=False)
    op.create_index('idx_concepts_metadata', 'concepts', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_concepts_name', 'concepts', ['name'], unique=False)
    op.create_index('idx_concepts_search', 'concepts', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('curriculum_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('curriculum_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_from_assessment', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version > 0', name='chk_curriculum_version'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='curriculum_plans_book_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_from_assessment'], ['assessments.id'], name='curriculum_plans_generated_from_assessment_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='curriculum_plans_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='curriculum_plans_pkey'),
    sa.UniqueConstraint('user_id', 'book_id', 'version', name='uq_curriculum_user_book_version'),
    comment='Generated learning order for a user on a book.'
    )
    op.create_index('idx_curriculum_book', 'curriculum_plans', ['book_id'], unique=False)
    op.create_index('idx_curriculum_json', 'curriculum_plans', ['curriculum_json'], unique=False, postgresql_using='gin')
    op.create_index('idx_curriculum_user', 'curriculum_plans', ['user_id'], unique=False)
    op.create_index('idx_curriculum_user_book_version', 'curriculum_plans', ['user_id', 'book_id', 'version'], unique=False)
    op.create_table('graph_build_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('graph_version', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('QUEUED', 'PARSING', 'CHUNKING', 'EXTRACTING_CONCEPTS', 'CANONICALIZING', 'EXTRACTING_RELATIONSHIPS', 'VALIDATING', 'REPAIRING', 'PUBLISHING', 'COMPLETED', 'FAILED', name='graph_build_status'), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('current_offset', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nodes_created', sa.Integer(), nullable=True),
    sa.Column('edges_created', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('book_upload_id', sa.UUID(), nullable=True),
    sa.Column('concepts_created', sa.Integer(), nullable=True),
    sa.Column('chunks_processed', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunks_processed IS NULL OR chunks_processed >= 0', name='chk_chunks_processed'),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name='chk_graph_job_time'),
    sa.CheckConstraint('concepts_created IS NULL OR concepts_created >= 0', name='chk_concepts_created'),
    sa.CheckConstraint('edges_created IS NULL OR edges_created >= 0', name='chk_edges_created'),
    sa.CheckConstraint('graph_version > 0', name='chk_graph_version_positive'),
    sa.CheckConstraint('nodes_created IS NULL OR nodes_created >= 0', name='chk_nodes_created'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='graph_build_jobs_book_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_upload_id'], ['book_uploads.id'], name='graph_build_jobs_book_upload_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='graph_build_jobs_pkey'),
    comment='Async pipeline job tracker. Only one COMPLETED build per (book, graph_version).'
    )
    op.create_index('idx_graph_build_jobs_book', 'graph_build_jobs', ['book_id'], unique=False)
    op.create_index('idx_graph_build_jobs_metadata', 'graph_build_jobs', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_graph_build_jobs_status', 'graph_build_jobs', ['status'], unique=False)
    op.create_index('idx_graph_build_jobs_version', 'graph_build_jobs', ['book_id', 'graph_version'], unique=False)
    op.create_index('uq_completed_graph_version', 'graph_build_jobs', ['book_id', 'graph_version'], unique=True, postgresql_where="(status = 'COMPLETED'::graph_build_status)")
    op.create_table('source_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('book_upload_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name='chk_chunk_index'),
    sa.CheckConstraint('page_start IS NULL AND page_end IS NULL OR page_start IS NOT NULL AND page_end IS NOT NULL AND page_end >= page_start', name='chk_page_numbers'),
    sa.CheckConstraint('token_count IS NULL OR token_count > 0', name='chk_token_count'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='source_chunks_book_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_upload_id'], ['book_uploads.id'], name='source_chunks_book_upload_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name='source_chunks_chapter_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='source_chunks_pkey'),
    sa.UniqueConstraint('book_id', 'chunk_index', name='uq_chunk_position'),
    comment='Text chunks from books. Every concept is traceable back to its source chunks.'
    )
    op.create_index('idx_source_chunks_book', 'source_chunks', ['book_id'], unique=False)
    op.create_index('idx_source_chunks_chapter', 'source_chunks', ['chapter_id'], unique=False)
    op.create_index('idx_source_chunks_metadata', 'source_chunks', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_source_chunks_position', 'source_chunks', ['book_id', 'chunk_index'], unique=False)
    op.create_table('assessment_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('mastery_estimate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('placement_state', postgresql.ENUM('MASTERED', 'READY', 'LEARNING', 'WEAK', 'UNKNOWN', name='placement_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('mastery_estimate >= 0::numeric AND mastery_estimate <= 1::numeric', name='chk_mastery_estimate'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name='assessment_outcomes_assessment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name='assessment_outcomes_concept_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='assessment_outcomes_pkey'),
    sa.UniqueConstraint('assessment_id', 'concept_id', name='uq_assessment_concept_outcome'),
    comment='Per-concept placement result seeding mastery and node_state.'
    )
    op.create_index('idx_assessment_outcomes_assessment', 'assessment_outcomes', ['assessment_id'], unique=False)
    op.create_index('idx_assessment_outcomes_concept', 'assessment_outcomes', ['concept_id'], unique=False)
    op.create_table('concept_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('relevance_score IS NULL OR relevance_score >= 0::numeric AND relevance_score <= 1::numeric', name='chk_relevance_score'),
    sa.ForeignKeyConstraint(['chunk_id'], ['source_chunks.id'], name='concept_chunks_chunk_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name='concept_chunks_concept_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='concept_chunks_pkey'),
    sa.UniqueConstraint('concept_id', 'chunk_id', name='uq_concept_chunk'),
    comment='Many-to-many: concept Γåö source chunks used to ground it.'
    )
    op.create_index('idx_concept_chunks_chunk', 'concept_chunks', ['chunk_id'], unique=False)
    op.create_index('idx_concept_chunks_concept', 'concept_chunks', ['concept_id'], unique=False)
    op.create_table('concept_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('graph_version', sa.Integer(), nullable=False),
    sa.Column('from_concept_id', sa.UUID(), nullable=False),
    sa.Column('to_concept_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', postgresql.ENUM('PREREQUISITE', 'RELATED', name='edge_type'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0::numeric AND confidence <= 1::numeric', name='chk_confidence'),
    sa.CheckConstraint('from_concept_id <> to_concept_id', name='chk_no_self_loop'),
    sa.CheckConstraint('graph_version > 0', name='chk_graph_version_edge'),
    sa.CheckConstraint('weight >= 0::numeric', name='chk_weight'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='concept_edges_book_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_concept_id'], ['concepts.id'], name='concept_edges_from_concept_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_concept_id'], ['concepts.id'], name='concept_edges_to_concept_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='concept_edges_pkey'),
    sa.UniqueConstraint('book_id', 'graph_version', 'from_concept_id', 'to_concept_id', 'edge_type', name='uq_concept_edge'),
    comment='KG edges ΓÇö prerequisite/related links between concepts forming a DAG. DAG invariant enforced at pipeline layer.'
    )
    op.create_index('idx_concept_edges_book', 'concept_edges', ['book_id', 'graph_version'], unique=False)
    op.create_index('idx_concept_edges_from', 'concept_edges', ['from_concept_id'], unique=False)
    op.create_index('idx_concept_edges_to', 'concept_edges', ['to_concept_id'], unique=False)
    op.create_index('idx_concept_edges_type', 'concept_edges', ['edge_type'], unique=False)
    op.create_index('idx_concept_edges_unverified', 'concept_edges', ['book_id'], unique=False, postgresql_where='(is_verified = false)')
    op.create_table('concept_fsrs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('retrievability', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('next_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_mastery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('mastery_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('retention_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('mastery_state', postgresql.ENUM('UNKNOWN', 'LEARNING', 'PRACTICING', 'MASTERED', 'FORGOTTEN', name='mastery_state'), nullable=False),
    sa.Column('first_mastered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_source', postgresql.ENUM('ASSESSMENT', 'LESSON', 'QUIZ', 'REVISION', 'MANUAL', name='review_source'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mastery_state <> 'MASTERED'::mastery_state OR first_mastered_at IS NOT NULL", name='chk_mastery_mastered_timestamp'),
    sa.CheckConstraint('mastery_score >= 0::numeric AND mastery_score <= 1::numeric', name='chk_mastery_score'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name='concept_mastery_concept_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='concept_mastery_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='concept_mastery_pkey'),
    sa.UniqueConstraint('user_id', 'concept_id', name='uq_user_concept_mastery'),
    comment='Source of truth for numeric mastery score per (user, concept).'
    )
    op.create_index('idx_concept_mastery_concept', 'concept_mastery', ['concept_id'], unique=False)
    op.create_index('idx_concept_mastery_score', 'concept_mastery', ['mastery_score'], unique=False)
    op.create_index('idx_concept_mastery_state', 'concept_mastery', ['mastery_state'], unique=False)
    op.create_index('idx_concept_mastery_user', 'concept_mastery', ['user_id'], unique=False)
    op.create_index('idx_concept_mastery_user_state', 'concept_mastery', ['user_id', 'mastery_state'], unique=False)
    op.create_index('idx_mastery_user_concept_score', 'concept_mastery', ['user_id', 'concept_id', 'mastery_score'], unique=False)
    op.create_table('fsrs_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('review_source', postgresql.ENUM('ASSESSMENT', 'LESSON', 'QUIZ', 'REVISION', 'MANUAL', name='review_source'), nullable=False),
    sa.Column('review_grade', sa.Integer(), nullable=False),
    sa.Column('stability_before', sa.Float(), nullable=True),
    sa.Column('stability_after', sa.Float(), nullable=True),
    sa.Column('difficulty_before', sa.Float(), nullable=True),
    sa.Column('difficulty_after', sa.Float(), nullable=True),
    sa.Column('retrievability_before', sa.Float(), nullable=True),
    sa.Column('retrievability_after', sa.Float(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('question_type', postgresql.ENUM('MCQ', 'TRUE_FALSE', 'SHORT_ANSWER', 'SCENARIO', 'ORDERING', 'MATCHING', name='question_type'), nullable=False),
    sa.Column('question_source', postgresql.ENUM('GENERATED', 'USER_ASKED', 'ASSESSMENT_MISS', 'REVISION', name='question_source'), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_key', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('generation_model', sa.String(length=100), nullable=True),
    sa.Column('generation_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('difficulty_level >= 1 AND difficulty_level <= 5', name='chk_question_difficulty'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name='generated_questions_concept_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='generated_questions_pkey'),
    comment='Questions per concept. source=USER_ASKED|ASSESSMENT_MISS powers targeted revision.'
    )
    op.create_index('idx_generated_questions_answer_key', 'generated_questions', ['answer_key'], unique=False, postgresql_using='gin')
    op.create_index('idx_generated_questions_concept', 'generated_questions', ['concept_id'], unique=False)
    op.create_index('idx_generated_questions_concept_source', 'generated_questions', ['concept_id', 'question_source'], unique=False)
    op.create_index('idx_generated_questions_difficulty', 'generated_questions', ['difficulty_level'], unique=False)
    op.create_index('idx_generated_questions_source', 'generated_questions', ['question_source'], unique=False)
    op.create_index('idx_generated_questions_type', 'generated_questions', ['question_type'], unique=False)
    op.create_table('graph_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('build_job_id', sa.UUID(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('edge_count >= 0', name='chk_gv_edge_count'),
    sa.CheckConstraint('node_count >= 0', name='chk_gv_node_count'),
    sa.CheckConstraint('version > 0', name='chk_gv_version'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='graph_versions_book_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['build_job_id'], ['graph_build_jobs.id'], name='graph_versions_build_job_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='graph_versions_pkey'),
    sa.UniqueConstraint('book_id', 'version', name='uq_graph_version_per_book'),
    comment='Named snapshot of each completed graph build per book. Single source for version lookups.'
    )
    op.create_index('idx_graph_versions_book', 'graph_versions', ['book_id'], unique=False)
    op.create_index('idx_graph_versions_current', 'graph_versions', ['book_id'], unique=False, postgresql_where='(is_current = true)')
    op.create_index('uq_current_graph_version_per_book', 'graph_versions', ['book_id'], unique=True, postgresql_where='(is_current = true)')
    op.create_table('lesson_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('curriculum_plan_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='lesson_status'), nullable=False),
    sa.Column('generated_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name='chk_lesson_time'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name='lesson_sessions_concept_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['curriculum_plan_id'], ['curriculum_plans.id'], name='lesson_sessions_curriculum_plan_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='lesson_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='lesson_sessions_pkey'),
    comment='One session = Socratic teaching of one concept.'
    )
    op.create_index('idx_active_lesson_sessions', 'lesson_sessions', ['user_id'], unique=False, postgresql_where="(status = 'IN_PROGRESS'::lesson_status)")
    op.create_index('idx_lesson_sessions_concept', 'lesson_sessions', ['concept_id'], unique=False)
    op.create_index('idx_lesson_sessions_content', 'lesson_sessions', ['generated_content'], unique=False, postgresql_using='gin')
    op.create_index('idx_lesson_sessions_status', 'lesson_sessions', ['status'], unique=False)
    op.create_index('idx_lesson_sessions_user', 'lesson_sessions', ['user_id'], unique=False)
    op.create_table('mastery_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('source', postgresql.ENUM('ASSESSMENT', 'LESSON', 'QUIZ', 'REVISION', 'MANUAL', name='review_source'), nullable=False),
    sa.Column('previous_mastery', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('new_mastery', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('new_mastery IS NULL OR new_mastery >= 0::numeric AND new_mastery <= 1::numeric', name='chk_new_mastery'),
    sa.CheckConstraint('previous_mastery IS NULL OR previous_mastery >= 0::numeric AND previous_mastery <= 1::numeric', name='chk_prev_mastery'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name='mastery_events_concept_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='mastery_events_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='mastery_events_pkey'),
    comment='Audit trail for every mastery_score change. Useful for visualization and debugging.'
    )
    op.create_index('idx_mastery_events_concept', 'mastery_events', ['concept_id'], unique=False)
    op.create_index('idx_mastery_events_created', 'mastery_events', ['created_at'], unique=False)
    op.create_index('idx_mastery_events_user', 'mastery_events', ['user_id'], unique=False)
    op.create_table('user_concept_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('graph_version', sa.Integer(), nullable=False),
    sa.Column('state', postgresql.ENUM('LOCKED', 'AVAILABLE', 'IN_PROGRESS', 'MASTERED', 'DUE', name='node_state'), nullable=False),
    sa.Column('state_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('graph_version > 0', name='chk_ucs_graph_version'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name='user_concept_state_concept_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_concept_state_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_concept_state_pkey'),
    sa.UniqueConstraint('user_id', 'concept_id', 'graph_version', name='uq_user_concept_state'),
    comment='DAG overlay per user: LOCKED|AVAILABLE|IN_PROGRESS|MASTERED|DUE. Drives graph reveal UI.'
    )
    op.create_index('idx_ucs_concept', 'user_concept_state', ['concept_id'], unique=False)
    op.create_index('idx_ucs_due', 'user_concept_state', ['user_id'], unique=False, postgresql_where="(state = 'DUE'::node_state)")
    op.create_index('idx_ucs_locked', 'user_concept_state', ['user_id'], unique=False, postgresql_where="(state = 'LOCKED'::node_state)")
    op.create_index('idx_ucs_state', 'user_concept_state', ['state'], unique=False)
    op.create_index('idx_ucs_user', 'user_concept_state', ['user_id'], unique=False)
    op.create_index('idx_ucs_user_state', 'user_concept_state', ['user_id', 'state'], unique=False)
    op.create_table('assessment_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('confidence_level', sa.Integer(), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_level IS NULL OR confidence_level >= 1 AND confidence_level <= 5', name='chk_confidence_response'),
    sa.CheckConstraint('response_time_seconds IS NULL OR response_time_seconds >= 0', name='chk_response_time'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name='assessment_responses_assessment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name='assessment_responses_concept_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['generated_questions.id'], name='assessment_responses_question_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='assessment_responses_pkey'),
    comment='Per-question responses. confidence_level before reveal = calibration signal.'
    )
    op.create_index('idx_assessment_responses_assessment', 'assessment_responses', ['assessment_id'], unique=False)
    op.create_index('idx_assessment_responses_concept', 'assessment_responses', ['concept_id'], unique=False)
    op.create_index('idx_assessment_responses_miss', 'assessment_responses', ['concept_id'], unique=False, postgresql_where='(is_correct = false)')
    op.create_index('idx_assessment_responses_question', 'assessment_responses', ['question_id'], unique=False)
    op.create_index('idx_assessment_responses_response', 'assessment_responses', ['response'], unique=False, postgresql_using='gin')
    op.create_table('evaluated_pairs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_version_id', sa.UUID(), nullable=False),
    sa.Column('source_concept_id', sa.UUID(), nullable=False),
    sa.Column('target_concept_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('llm_version', sa.String(length=50), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graph_version_id'], ['graph_versions.id'], name='evaluated_pairs_graph_version_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_concept_id'], ['concepts.id'], name='evaluated_pairs_source_concept_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_concept_id'], ['concepts.id'], name='evaluated_pairs_target_concept_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='evaluated_pairs_pkey'),
    sa.UniqueConstraint('graph_version_id', 'source_concept_id', 'target_concept_id', name='uq_evaluated_pairs_version_src_tgt')
    )
    op.create_index('ix_evaluated_pairs_version', 'evaluated_pairs', ['graph_version_id'], unique=False)
    op.create_table('graph_audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_version_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['graph_version_id'], ['graph_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_repair_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_version_id', sa.UUID(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('before_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graph_version_id'], ['graph_versions.id'], name='graph_repair_log_graph_version_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='graph_repair_log_pkey')
    )
    op.create_table('graph_validation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_version_id', sa.UUID(), nullable=True),
    sa.Column('rule_code', sa.Text(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graph_version_id'], ['graph_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_version_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_version_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['graph_version_id'], ['graph_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_version_id', sa.UUID(), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('subtopics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('canonical_concept_id', sa.UUID(), nullable=True),
    sa.Column('canonicalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_concept_id'], ['concepts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['graph_version_id'], ['graph_versions.id'], name='raw_concepts_graph_version_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='raw_concepts_pkey')
    )
    op.create_index('ix_raw_concepts_chunk', 'raw_concepts', ['source_chunk_id'], unique=False)
    op.create_index('ix_raw_concepts_version', 'raw_concepts', ['graph_version_id'], unique=False)
    op.create_table('relationship_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_version_id', sa.UUID(), nullable=False),
    sa.Column('source_concept_id', sa.UUID(), nullable=False),
    sa.Column('target_concept_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graph_version_id'], ['graph_versions.id'], name='relationship_candidates_graph_version_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_concept_id'], ['concepts.id'], name='relationship_candidates_source_concept_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_concept_id'], ['concepts.id'], name='relationship_candidates_target_concept_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='relationship_candidates_pkey')
    )
    op.create_index('ix_rel_candidates_version_status', 'relationship_candidates', ['graph_version_id', 'status'], unique=False)
    op.create_table('tutor_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_session_id', sa.UUID(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('assistant_message', sa.Text(), nullable=False),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('token_input_count', sa.Integer(), nullable=True),
    sa.Column('token_output_count', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hint_level >= 0 AND hint_level <= 4', name='chk_hint_level'),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name='chk_latency'),
    sa.CheckConstraint('token_input_count IS NULL OR token_input_count >= 0', name='chk_input_tokens'),
    sa.CheckConstraint('token_output_count IS NULL OR token_output_count >= 0', name='chk_output_tokens'),
    sa.CheckConstraint('turn_index >= 0', name='chk_turn_index'),
    sa.ForeignKeyConstraint(['lesson_session_id'], ['lesson_sessions.id'], name='tutor_interactions_lesson_session_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['generated_questions.id'], name='tutor_interactions_question_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='tutor_interactions_pkey'),
    sa.UniqueConstraint('lesson_session_id', 'turn_index', name='uq_session_turn'),
    comment='Immutable turn-by-turn Socratic conversation log with turn_index ordering.'
    )
    op.create_index('idx_tutor_interactions_created', 'tutor_interactions', ['created_at'], unique=False)
    op.create_index('idx_tutor_interactions_question', 'tutor_interactions', ['question_id'], unique=False, postgresql_where='(question_id IS NOT NULL)')
    op.create_index('idx_tutor_interactions_session', 'tutor_interactions', ['lesson_session_id'], unique=False)
    op.create_table('user_books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('pinned_graph_version_id', sa.UUID(), nullable=True),
    sa.Column('current_chapter_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='user_books_book_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_chapter_id'], ['chapters.id'], name='user_books_current_chapter_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pinned_graph_version_id'], ['graph_versions.id'], name='user_books_pinned_graph_version_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_books_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_books_pkey'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_user_book'),
    comment='User enrollment in a book. Pins graph version at enrollment time.'
    )
    op.create_index('idx_user_books_book', 'user_books', ['book_id'], unique=False)
    op.create_index('idx_user_books_user', 'user_books', ['user_id'], unique=False)
    op.create_index('idx_user_books_version', 'user_books', ['pinned_graph_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_books_version', table_name='user_books')
    op.drop_index('idx_user_books_user', table_name='user_books')
    op.drop_index('idx_user_books_book', table_name='user_books')
    op.drop_table('user_books')
    op.drop_index('idx_tutor_interactions_session', table_name='tutor_interactions')
    op.drop_index('idx_tutor_interactions_question', table_name='tutor_interactions', postgresql_where='(question_id IS NOT NULL)')
    op.drop_index('idx_tutor_interactions_created', table_name='tutor_interactions')
    op.drop_table('tutor_interactions')
    op.drop_index('ix_rel_candidates_version_status', table_name='relationship_candidates')
    op.drop_table('relationship_candidates')
    op.drop_index('ix_raw_concepts_version', table_name='raw_concepts')
    op.drop_index('ix_raw_concepts_chunk', table_name='raw_concepts')
    op.drop_table('raw_concepts')
    op.drop_table('graph_version_events')
    op.drop_table('graph_validation_results')
    op.drop_table('graph_repair_log')
    op.drop_table('graph_audit_events')
    op.drop_index('ix_evaluated_pairs_version', table_name='evaluated_pairs')
    op.drop_table('evaluated_pairs')
    op.drop_index('idx_assessment_responses_response', table_name='assessment_responses', postgresql_using='gin')
    op.drop_index('idx_assessment_responses_question', table_name='assessment_responses')
    op.drop_index('idx_assessment_responses_miss', table_name='assessment_responses', postgresql_where='(is_correct = false)')
    op.drop_index('idx_assessment_responses_concept', table_name='assessment_responses')
    op.drop_index('idx_assessment_responses_assessment', table_name='assessment_responses')
    op.drop_table('assessment_responses')
    op.drop_index('idx_ucs_user_state', table_name='user_concept_state')
    op.drop_index('idx_ucs_user', table_name='user_concept_state')
    op.drop_index('idx_ucs_state', table_name='user_concept_state')
    op.drop_index('idx_ucs_locked', table_name='user_concept_state', postgresql_where="(state = 'LOCKED'::node_state)")
    op.drop_index('idx_ucs_due', table_name='user_concept_state', postgresql_where="(state = 'DUE'::node_state)")
    op.drop_index('idx_ucs_concept', table_name='user_concept_state')
    op.drop_table('user_concept_state')
    op.drop_index('idx_mastery_events_user', table_name='mastery_events')
    op.drop_index('idx_mastery_events_created', table_name='mastery_events')
    op.drop_index('idx_mastery_events_concept', table_name='mastery_events')
    op.drop_table('mastery_events')
    op.drop_index('idx_lesson_sessions_user', table_name='lesson_sessions')
    op.drop_index('idx_lesson_sessions_status', table_name='lesson_sessions')
    op.drop_index('idx_lesson_sessions_content', table_name='lesson_sessions', postgresql_using='gin')
    op.drop_index('idx_lesson_sessions_concept', table_name='lesson_sessions')
    op.drop_index('idx_active_lesson_sessions', table_name='lesson_sessions', postgresql_where="(status = 'IN_PROGRESS'::lesson_status)")
    op.drop_table('lesson_sessions')
    op.drop_index('uq_current_graph_version_per_book', table_name='graph_versions', postgresql_where='(is_current = true)')
    op.drop_index('idx_graph_versions_current', table_name='graph_versions', postgresql_where='(is_current = true)')
    op.drop_index('idx_graph_versions_book', table_name='graph_versions')
    op.drop_table('graph_versions')
    op.drop_index('idx_generated_questions_type', table_name='generated_questions')
    op.drop_index('idx_generated_questions_source', table_name='generated_questions')
    op.drop_index('idx_generated_questions_difficulty', table_name='generated_questions')
    op.drop_index('idx_generated_questions_concept_source', table_name='generated_questions')
    op.drop_index('idx_generated_questions_concept', table_name='generated_questions')
    op.drop_index('idx_generated_questions_answer_key', table_name='generated_questions', postgresql_using='gin')
    op.drop_table('generated_questions')
    op.drop_table('fsrs_reviews')
    op.drop_index('idx_mastery_user_concept_score', table_name='concept_mastery')
    op.drop_index('idx_concept_mastery_user_state', table_name='concept_mastery')
    op.drop_index('idx_concept_mastery_user', table_name='concept_mastery')
    op.drop_index('idx_concept_mastery_state', table_name='concept_mastery')
    op.drop_index('idx_concept_mastery_score', table_name='concept_mastery')
    op.drop_index('idx_concept_mastery_concept', table_name='concept_mastery')
    op.drop_table('concept_mastery')
    op.drop_table('concept_fsrs')
    op.drop_index('idx_concept_edges_unverified', table_name='concept_edges', postgresql_where='(is_verified = false)')
    op.drop_index('idx_concept_edges_type', table_name='concept_edges')
    op.drop_index('idx_concept_edges_to', table_name='concept_edges')
    op.drop_index('idx_concept_edges_from', table_name='concept_edges')
    op.drop_index('idx_concept_edges_book', table_name='concept_edges')
    op.drop_table('concept_edges')
    op.drop_index('idx_concept_chunks_concept', table_name='concept_chunks')
    op.drop_index('idx_concept_chunks_chunk', table_name='concept_chunks')
    op.drop_table('concept_chunks')
    op.drop_index('idx_assessment_outcomes_concept', table_name='assessment_outcomes')
    op.drop_index('idx_assessment_outcomes_assessment', table_name='assessment_outcomes')
    op.drop_table('assessment_outcomes')
    op.drop_index('idx_source_chunks_position', table_name='source_chunks')
    op.drop_index('idx_source_chunks_metadata', table_name='source_chunks', postgresql_using='gin')
    op.drop_index('idx_source_chunks_chapter', table_name='source_chunks')
    op.drop_index('idx_source_chunks_book', table_name='source_chunks')
    op.drop_table('source_chunks')
    op.drop_index('uq_completed_graph_version', table_name='graph_build_jobs', postgresql_where="(status = 'COMPLETED'::graph_build_status)")
    op.drop_index('idx_graph_build_jobs_version', table_name='graph_build_jobs')
    op.drop_index('idx_graph_build_jobs_status', table_name='graph_build_jobs')
    op.drop_index('idx_graph_build_jobs_metadata', table_name='graph_build_jobs', postgresql_using='gin')
    op.drop_index('idx_graph_build_jobs_book', table_name='graph_build_jobs')
    op.drop_table('graph_build_jobs')
    op.drop_index('idx_curriculum_user_book_version', table_name='curriculum_plans')
    op.drop_index('idx_curriculum_user', table_name='curriculum_plans')
    op.drop_index('idx_curriculum_json', table_name='curriculum_plans', postgresql_using='gin')
    op.drop_index('idx_curriculum_book', table_name='curriculum_plans')
    op.drop_table('curriculum_plans')
    op.drop_index('idx_concepts_search', table_name='concepts', postgresql_using='gin')
    op.drop_index('idx_concepts_name', table_name='concepts')
    op.drop_index('idx_concepts_metadata', table_name='concepts', postgresql_using='gin')
    op.drop_index('idx_concepts_graph_version', table_name='concepts')
    op.drop_index('idx_concepts_difficulty', table_name='concepts')
    op.drop_index('idx_concepts_chapter', table_name='concepts')
    op.drop_index('idx_concepts_book', table_name='concepts')
    op.drop_table('concepts')
    op.drop_index('idx_progress_user_book', table_name='progress_snapshots')
    op.drop_index('idx_progress_snapshots_user', table_name='progress_snapshots')
    op.drop_index('idx_progress_snapshots_date', table_name='progress_snapshots')
    op.drop_index('idx_progress_snapshots_book', table_name='progress_snapshots')
    op.drop_table('progress_snapshots')
    op.drop_table('daily_plans')
    op.drop_index('idx_chapters_number', table_name='chapters')
    op.drop_index('idx_chapters_book_id', table_name='chapters')
    op.drop_table('chapters')
    op.drop_table('book_uploads')
    op.drop_index('idx_book_streaks_user', table_name='book_streaks')
    op.drop_index('idx_book_streaks_book', table_name='book_streaks')
    op.drop_table('book_streaks')
    op.drop_index('idx_assessments_user', table_name='assessments')
    op.drop_index('idx_assessments_status', table_name='assessments')
    op.drop_index('idx_assessments_book', table_name='assessments')
    op.drop_index('idx_assessment_user_book', table_name='assessments')
    op.drop_index('idx_active_assessments', table_name='assessments', postgresql_where="(status = 'IN_PROGRESS'::assessment_status)")
    op.drop_table('assessments')
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_index('idx_notifications_unread', table_name='notifications', postgresql_where='(is_read = false)')
    op.drop_table('notifications')
    op.drop_table('learning_streaks')
    op.drop_index('uq_active_dna_per_user', table_name='learning_dna', postgresql_where='(is_active = true)')
    op.drop_index('idx_learning_dna_user', table_name='learning_dna')
    op.drop_index('idx_learning_dna_data', table_name='learning_dna', postgresql_using='gin')
    op.drop_table('learning_dna')
    op.drop_table('learner_profiles')
    op.drop_index('idx_daily_activity_user_date', table_name='daily_activity')
    op.drop_index('idx_daily_activity_user', table_name='daily_activity')
    op.drop_index('idx_daily_activity_date', table_name='daily_activity')
    op.drop_table('daily_activity')
    op.drop_index('idx_content_completions_user', table_name='content_completions')
    op.drop_index('idx_content_completions_content', table_name='content_completions')
    op.drop_table('content_completions')
    op.drop_index('idx_books_visibility', table_name='books')
    op.drop_index('idx_books_title', table_name='books')
    op.drop_index('idx_books_status', table_name='books')
    op.drop_index('idx_books_owner', table_name='books')
    op.drop_index('idx_books_created_at', table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_active', table_name='users', postgresql_where='(is_active = true)')
    op.drop_table('users')
    # ### end Alembic commands ###
